var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import cookieParser from "cookie-parser";
import express2 from "express";
import cors from "cors";

// src/config/index.ts
import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env") });
var config_default = {
  port: process.env.PORT,
  database_url: process.env.DATABASE_URL,
  app_url: process.env.APP_URL,
  bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
  jwt_access_secret: process.env.JWT_ACCESS_SECRET,
  jwt_refresh_secret: process.env.JWT_REFRESH_SECRET,
  jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN,
  jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN,
  stripe_secret_key: process.env.STRIPE_SECRET_KEY,
  stripe_publishable_key: process.env.STRIPE_PUBLISHABLE_KEY,
  stripe_webhook_secret: process.env.STRIPE_WEBHOOK_SECRET
};

// src/modules/auth/route.ts
import { Router } from "express";

// src/utils/catchAsync.ts
import httpStatus from "http-status";
var catchAsync = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      console.log(error);
      res.status(httpStatus.INTERNAL_SERVER_ERROR).json({
        success: false,
        statusCode: httpStatus.INTERNAL_SERVER_ERROR,
        message: "Failed to register user",
        error: error.message
      });
    }
  };
};

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// src/generated/prisma/client.ts
import * as path2 from "path";
import { fileURLToPath } from "url";

// src/generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.9.1",
  "engineVersion": "e922089b7d7502aff4249d5da3420f6fa55fc6ad",
  "activeProvider": "postgresql",
  "inlineSchema": 'model Category {\n  id          String  @id @default(uuid())\n  name        String  @unique\n  description String?\n\n  properties Property[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@map("categories")\n}\n\nenum UserRole {\n  TENANT\n  LANDLORD\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  BANNED\n}\n\nenum PropertyStatus {\n  AVAILABLE\n  RESERVED\n  RENTED\n  UNAVAILABLE\n}\n\nenum RentalRequestStatus {\n  PENDING\n  APPROVED\n  REJECTED\n  ACTIVE\n  COMPLETED\n}\n\nenum PaymentProvider {\n  STRIPE\n  SSLCOMMERZ\n}\n\nenum PaymentStatus {\n  PENDING\n  SUCCESS\n  FAILED\n  REFUNDED\n}\n\nmodel Payment {\n  id              String @id @default(uuid())\n  rentalRequestId String @unique\n\n  transactionId String  @unique\n  amount        Decimal @db.Decimal(10, 2)\n\n  provider      PaymentProvider\n  paymentMethod String?\n\n  status PaymentStatus @default(PENDING)\n  paidAt DateTime?\n\n  rentalRequest RentalRequest @relation(fields: [rentalRequestId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([status])\n  @@index([provider])\n  @@map("payments")\n}\n\nmodel Profile {\n  id           String   @id @default(uuid())\n  profilePhoto String?\n  bio          String?\n  userId       String   @unique\n  createdAt    DateTime @default(now())\n  updatedAt    DateTime @updatedAt\n  user         User     @relation(fields: [userId], references: [id])\n\n  @@map("profiles")\n}\n\nmodel Property {\n  id         String @id @default(uuid())\n  landlordId String\n  categoryId String\n\n  title        String\n  description  String\n  address      String\n  city         String\n  propertyType String\n\n  bedrooms  Int\n  bathrooms Int\n\n  rentPrice Decimal @db.Decimal(10, 2)\n\n  amenities String[]\n  images    String[]\n\n  status PropertyStatus @default(AVAILABLE)\n\n  landlord User @relation("LandlordProperties", fields: [landlordId], references: [id], onDelete: Cascade)\n\n  category Category @relation(fields: [categoryId], references: [id])\n\n  rentalRequests RentalRequest[]\n  reviews        Review[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([landlordId])\n  @@index([categoryId])\n  @@index([city])\n  @@index([rentPrice])\n  @@map("properties")\n}\n\nmodel RentalRequest {\n  id         String @id @default(uuid())\n  tenantId   String\n  propertyId String\n\n  moveInDate  DateTime\n  duration    Int\n  monthlyRent Decimal  @db.Decimal(10, 2)\n\n  status     RentalRequestStatus @default(PENDING)\n  approvedAt DateTime?\n\n  tenant User @relation("TenantRequests", fields: [tenantId], references: [id], onDelete: Cascade)\n\n  property Property @relation(fields: [propertyId], references: [id], onDelete: Cascade)\n\n  payment Payment?\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([tenantId])\n  @@index([propertyId])\n  @@index([status])\n  @@map("rental_requests")\n}\n\nmodel Review {\n  id         String @id @default(uuid())\n  tenantId   String\n  propertyId String\n\n  rating  Int\n  comment String?\n\n  tenant User @relation("TenantReviews", fields: [tenantId], references: [id], onDelete: Cascade)\n\n  property Property @relation(fields: [propertyId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@unique([tenantId, propertyId])\n  @@index([propertyId])\n  @@map("reviews")\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Get a free hosted Postgres database in seconds: `npx create-db`\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../src/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id       String     @id @default(uuid())\n  name     String     @db.VarChar(255)\n  email    String     @unique\n  password String\n  phone    String?\n  role     UserRole   @default(TENANT)\n  status   UserStatus @default(ACTIVE)\n  profile  Profile?\n\n  properties     Property[]      @relation("LandlordProperties")\n  rentalRequests RentalRequest[] @relation("TenantRequests")\n  reviews        Review[]        @relation("TenantReviews")\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@map("users")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"properties","kind":"object","type":"Property","relationName":"CategoryToProperty"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"categories"},"Payment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rentalRequestId","kind":"scalar","type":"String"},{"name":"transactionId","kind":"scalar","type":"String"},{"name":"amount","kind":"scalar","type":"Decimal"},{"name":"provider","kind":"enum","type":"PaymentProvider"},{"name":"paymentMethod","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"PaymentStatus"},{"name":"paidAt","kind":"scalar","type":"DateTime"},{"name":"rentalRequest","kind":"object","type":"RentalRequest","relationName":"PaymentToRentalRequest"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"payments"},"Profile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"profilePhoto","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"ProfileToUser"}],"dbName":"profiles"},"Property":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"landlordId","kind":"scalar","type":"String"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"address","kind":"scalar","type":"String"},{"name":"city","kind":"scalar","type":"String"},{"name":"propertyType","kind":"scalar","type":"String"},{"name":"bedrooms","kind":"scalar","type":"Int"},{"name":"bathrooms","kind":"scalar","type":"Int"},{"name":"rentPrice","kind":"scalar","type":"Decimal"},{"name":"amenities","kind":"scalar","type":"String"},{"name":"images","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"PropertyStatus"},{"name":"landlord","kind":"object","type":"User","relationName":"LandlordProperties"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToProperty"},{"name":"rentalRequests","kind":"object","type":"RentalRequest","relationName":"PropertyToRentalRequest"},{"name":"reviews","kind":"object","type":"Review","relationName":"PropertyToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"properties"},"RentalRequest":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"tenantId","kind":"scalar","type":"String"},{"name":"propertyId","kind":"scalar","type":"String"},{"name":"moveInDate","kind":"scalar","type":"DateTime"},{"name":"duration","kind":"scalar","type":"Int"},{"name":"monthlyRent","kind":"scalar","type":"Decimal"},{"name":"status","kind":"enum","type":"RentalRequestStatus"},{"name":"approvedAt","kind":"scalar","type":"DateTime"},{"name":"tenant","kind":"object","type":"User","relationName":"TenantRequests"},{"name":"property","kind":"object","type":"Property","relationName":"PropertyToRentalRequest"},{"name":"payment","kind":"object","type":"Payment","relationName":"PaymentToRentalRequest"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"rental_requests"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"tenantId","kind":"scalar","type":"String"},{"name":"propertyId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"tenant","kind":"object","type":"User","relationName":"TenantReviews"},{"name":"property","kind":"object","type":"Property","relationName":"PropertyToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"reviews"},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"UserRole"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"profile","kind":"object","type":"Profile","relationName":"ProfileToUser"},{"name":"properties","kind":"object","type":"Property","relationName":"LandlordProperties"},{"name":"rentalRequests","kind":"object","type":"RentalRequest","relationName":"TenantRequests"},{"name":"reviews","kind":"object","type":"Review","relationName":"TenantReviews"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"users"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","profile","properties","tenant","property","rentalRequest","payment","rentalRequests","reviews","_count","landlord","category","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","data","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","create","update","Category.upsertOne","Category.deleteOne","Category.deleteMany","having","_min","_max","Category.groupBy","Category.aggregate","Payment.findUnique","Payment.findUniqueOrThrow","Payment.findFirst","Payment.findFirstOrThrow","Payment.findMany","Payment.createOne","Payment.createMany","Payment.createManyAndReturn","Payment.updateOne","Payment.updateMany","Payment.updateManyAndReturn","Payment.upsertOne","Payment.deleteOne","Payment.deleteMany","_avg","_sum","Payment.groupBy","Payment.aggregate","Profile.findUnique","Profile.findUniqueOrThrow","Profile.findFirst","Profile.findFirstOrThrow","Profile.findMany","Profile.createOne","Profile.createMany","Profile.createManyAndReturn","Profile.updateOne","Profile.updateMany","Profile.updateManyAndReturn","Profile.upsertOne","Profile.deleteOne","Profile.deleteMany","Profile.groupBy","Profile.aggregate","Property.findUnique","Property.findUniqueOrThrow","Property.findFirst","Property.findFirstOrThrow","Property.findMany","Property.createOne","Property.createMany","Property.createManyAndReturn","Property.updateOne","Property.updateMany","Property.updateManyAndReturn","Property.upsertOne","Property.deleteOne","Property.deleteMany","Property.groupBy","Property.aggregate","RentalRequest.findUnique","RentalRequest.findUniqueOrThrow","RentalRequest.findFirst","RentalRequest.findFirstOrThrow","RentalRequest.findMany","RentalRequest.createOne","RentalRequest.createMany","RentalRequest.createManyAndReturn","RentalRequest.updateOne","RentalRequest.updateMany","RentalRequest.updateManyAndReturn","RentalRequest.upsertOne","RentalRequest.deleteOne","RentalRequest.deleteMany","RentalRequest.groupBy","RentalRequest.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","AND","OR","NOT","id","name","email","password","phone","UserRole","role","UserStatus","status","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","every","some","none","tenantId","propertyId","rating","comment","moveInDate","duration","monthlyRent","RentalRequestStatus","approvedAt","landlordId","categoryId","title","description","address","city","propertyType","bedrooms","bathrooms","rentPrice","amenities","images","PropertyStatus","has","hasEvery","hasSome","profilePhoto","bio","userId","rentalRequestId","transactionId","amount","PaymentProvider","provider","paymentMethod","PaymentStatus","paidAt","tenantId_propertyId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","push","increment","decrement","multiply","divide"]'),
  graph: "1gNEcAkFAADXAQAghwEAAP4BADCIAQAAHQAQiQEAAP4BADCKAQEAAAABiwEBAAAAAZMBQADVAQAhlAFAANUBACGvAQEA0gEAIQEAAAABACAXCgAA2AEAIAsAANkBACANAADvAQAgDgAAiAIAIIcBAACGAgAwiAEAAAMAEIkBAACGAgAwigEBANEBACGSAQAAhwK5ASKTAUAA1QEAIZQBQADVAQAhrAEBANEBACGtAQEA0QEAIa4BAQDRAQAhrwEBANEBACGwAQEA0QEAIbEBAQDRAQAhsgEBANEBACGzAQIAgQIAIbQBAgCBAgAhtQEQAPgBACG2AQAA6QEAILcBAADpAQAgBAoAAPcCACALAAD4AgAgDQAAjwMAIA4AAKgDACAXCgAA2AEAIAsAANkBACANAADvAQAgDgAAiAIAIIcBAACGAgAwiAEAAAMAEIkBAACGAgAwigEBAAAAAZIBAACHArkBIpMBQADVAQAhlAFAANUBACGsAQEA0QEAIa0BAQDRAQAhrgEBANEBACGvAQEA0QEAIbABAQDRAQAhsQEBANEBACGyAQEA0QEAIbMBAgCBAgAhtAECAIECACG1ARAA-AEAIbYBAADpAQAgtwEAAOkBACADAAAAAwAgAQAABAAwAgAABQAgCgMAAO8BACCHAQAA7gEAMIgBAAAHABCJAQAA7gEAMIoBAQDRAQAhkwFAANUBACGUAUAA1QEAIbwBAQDSAQAhvQEBANIBACG-AQEA0QEAIQEAAAAHACADAAAAAwAgAQAABAAwAgAABQAgEAYAAO8BACAHAACCAgAgCQAAhQIAIIcBAACDAgAwiAEAAAoAEIkBAACDAgAwigEBANEBACGSAQAAhAKrASKTAUAA1QEAIZQBQADVAQAhowEBANEBACGkAQEA0QEAIacBQADVAQAhqAECAIECACGpARAA-AEAIasBQAD7AQAhBAYAAI8DACAHAACmAwAgCQAApwMAIKsBAACJAgAgEAYAAO8BACAHAACCAgAgCQAAhQIAIIcBAACDAgAwiAEAAAoAEIkBAACDAgAwigEBAAAAAZIBAACEAqsBIpMBQADVAQAhlAFAANUBACGjAQEA0QEAIaQBAQDRAQAhpwFAANUBACGoAQIAgQIAIakBEAD4AQAhqwFAAPsBACEDAAAACgAgAQAACwAwAgAADAAgDggAAPwBACCHAQAA9wEAMIgBAAAOABCJAQAA9wEAMIoBAQDRAQAhkgEAAPoBxgEikwFAANUBACGUAUAA1QEAIb8BAQDRAQAhwAEBANEBACHBARAA-AEAIcMBAAD5AcMBIsQBAQDSAQAhxgFAAPsBACEBAAAADgAgDAYAAO8BACAHAACCAgAghwEAAIACADCIAQAAEAAQiQEAAIACADCKAQEA0QEAIZMBQADVAQAhlAFAANUBACGjAQEA0QEAIaQBAQDRAQAhpQECAIECACGmAQEA0gEAIQMGAACPAwAgBwAApgMAIKYBAACJAgAgDQYAAO8BACAHAACCAgAghwEAAIACADCIAQAAEAAQiQEAAIACADCKAQEAAAABkwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGlAQIAgQIAIaYBAQDSAQAhxwEAAP8BACADAAAAEAAgAQAAEQAwAgAAEgAgAQAAAAMAIAEAAAAKACABAAAAEAAgAwAAAAoAIAEAAAsAMAIAAAwAIAMAAAAQACABAAARADACAAASACABAAAACgAgAQAAABAAIAEAAAADACABAAAAAQAgCQUAANcBACCHAQAA_gEAMIgBAAAdABCJAQAA_gEAMIoBAQDRAQAhiwEBANEBACGTAUAA1QEAIZQBQADVAQAhrwEBANIBACECBQAA9gIAIK8BAACJAgAgAwAAAB0AIAEAAB4AMAIAAAEAIAMAAAAdACABAAAeADACAAABACADAAAAHQAgAQAAHgAwAgAAAQAgBgUAAKUDACCKAQEAAAABiwEBAAAAAZMBQAAAAAGUAUAAAAABrwEBAAAAAQEUAAAiACAFigEBAAAAAYsBAQAAAAGTAUAAAAABlAFAAAAAAa8BAQAAAAEBFAAAJAAwARQAACQAMAYFAACbAwAgigEBAI0CACGLAQEAjQIAIZMBQACRAgAhlAFAAJECACGvAQEAjgIAIQIAAAABACAUAAAnACAFigEBAI0CACGLAQEAjQIAIZMBQACRAgAhlAFAAJECACGvAQEAjgIAIQIAAAAdACAUAAApACACAAAAHQAgFAAAKQAgAwAAAAEAIBsAACIAIBwAACcAIAEAAAABACABAAAAHQAgBAwAAJgDACAhAACaAwAgIgAAmQMAIK8BAACJAgAgCIcBAAD9AQAwiAEAADAAEIkBAAD9AQAwigEBAL8BACGLAQEAvwEAIZMBQADDAQAhlAFAAMMBACGvAQEAwAEAIQMAAAAdACABAAAvADAgAAAwACADAAAAHQAgAQAAHgAwAgAAAQAgDggAAPwBACCHAQAA9wEAMIgBAAAOABCJAQAA9wEAMIoBAQAAAAGSAQAA-gHGASKTAUAA1QEAIZQBQADVAQAhvwEBAAAAAcABAQAAAAHBARAA-AEAIcMBAAD5AcMBIsQBAQDSAQAhxgFAAPsBACEBAAAAMwAgAQAAADMAIAMIAACXAwAgxAEAAIkCACDGAQAAiQIAIAMAAAAOACABAAA2ADACAAAzACADAAAADgAgAQAANgAwAgAAMwAgAwAAAA4AIAEAADYAMAIAADMAIAsIAACWAwAgigEBAAAAAZIBAAAAxgECkwFAAAAAAZQBQAAAAAG_AQEAAAABwAEBAAAAAcEBEAAAAAHDAQAAAMMBAsQBAQAAAAHGAUAAAAABARQAADoAIAqKAQEAAAABkgEAAADGAQKTAUAAAAABlAFAAAAAAb8BAQAAAAHAAQEAAAABwQEQAAAAAcMBAAAAwwECxAEBAAAAAcYBQAAAAAEBFAAAPAAwARQAADwAMAsIAACVAwAgigEBAI0CACGSAQAAuwLGASKTAUAAkQIAIZQBQACRAgAhvwEBAI0CACHAAQEAjQIAIcEBEACvAgAhwwEAALoCwwEixAEBAI4CACHGAUAAsQIAIQIAAAAzACAUAAA_ACAKigEBAI0CACGSAQAAuwLGASKTAUAAkQIAIZQBQACRAgAhvwEBAI0CACHAAQEAjQIAIcEBEACvAgAhwwEAALoCwwEixAEBAI4CACHGAUAAsQIAIQIAAAAOACAUAABBACACAAAADgAgFAAAQQAgAwAAADMAIBsAADoAIBwAAD8AIAEAAAAzACABAAAADgAgBwwAAJADACAhAACTAwAgIgAAkgMAIDMAAJEDACA0AACUAwAgxAEAAIkCACDGAQAAiQIAIA2HAQAA8AEAMIgBAABIABCJAQAA8AEAMIoBAQC_AQAhkgEAAPIBxgEikwFAAMMBACGUAUAAwwEAIb8BAQC_AQAhwAEBAL8BACHBARAA3wEAIcMBAADxAcMBIsQBAQDAAQAhxgFAAOEBACEDAAAADgAgAQAARwAwIAAASAAgAwAAAA4AIAEAADYAMAIAADMAIAoDAADvAQAghwEAAO4BADCIAQAABwAQiQEAAO4BADCKAQEAAAABkwFAANUBACGUAUAA1QEAIbwBAQDSAQAhvQEBANIBACG-AQEAAAABAQAAAEsAIAEAAABLACADAwAAjwMAILwBAACJAgAgvQEAAIkCACADAAAABwAgAQAATgAwAgAASwAgAwAAAAcAIAEAAE4AMAIAAEsAIAMAAAAHACABAABOADACAABLACAHAwAAjgMAIIoBAQAAAAGTAUAAAAABlAFAAAAAAbwBAQAAAAG9AQEAAAABvgEBAAAAAQEUAABSACAGigEBAAAAAZMBQAAAAAGUAUAAAAABvAEBAAAAAb0BAQAAAAG-AQEAAAABARQAAFQAMAEUAABUADAHAwAAjQMAIIoBAQCNAgAhkwFAAJECACGUAUAAkQIAIbwBAQCOAgAhvQEBAI4CACG-AQEAjQIAIQIAAABLACAUAABXACAGigEBAI0CACGTAUAAkQIAIZQBQACRAgAhvAEBAI4CACG9AQEAjgIAIb4BAQCNAgAhAgAAAAcAIBQAAFkAIAIAAAAHACAUAABZACADAAAASwAgGwAAUgAgHAAAVwAgAQAAAEsAIAEAAAAHACAFDAAAigMAICEAAIwDACAiAACLAwAgvAEAAIkCACC9AQAAiQIAIAmHAQAA7QEAMIgBAABgABCJAQAA7QEAMIoBAQC_AQAhkwFAAMMBACGUAUAAwwEAIbwBAQDAAQAhvQEBAMABACG-AQEAvwEAIQMAAAAHACABAABfADAgAABgACADAAAABwAgAQAATgAwAgAASwAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAUCgAA6gIAIAsAAOsCACANAACJAwAgDgAA6QIAIIoBAQAAAAGSAQAAALkBApMBQAAAAAGUAUAAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEBAAAAAbABAQAAAAGxAQEAAAABsgEBAAAAAbMBAgAAAAG0AQIAAAABtQEQAAAAAbYBAADnAgAgtwEAAOgCACABFAAAaAAgEIoBAQAAAAGSAQAAALkBApMBQAAAAAGUAUAAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEBAAAAAbABAQAAAAGxAQEAAAABsgEBAAAAAbMBAgAAAAG0AQIAAAABtQEQAAAAAbYBAADnAgAgtwEAAOgCACABFAAAagAwARQAAGoAMBQKAADOAgAgCwAAzwIAIA0AAIgDACAOAADNAgAgigEBAI0CACGSAQAAywK5ASKTAUAAkQIAIZQBQACRAgAhrAEBAI0CACGtAQEAjQIAIa4BAQCNAgAhrwEBAI0CACGwAQEAjQIAIbEBAQCNAgAhsgEBAI0CACGzAQIAoAIAIbQBAgCgAgAhtQEQAK8CACG2AQAAyQIAILcBAADKAgAgAgAAAAUAIBQAAG0AIBCKAQEAjQIAIZIBAADLArkBIpMBQACRAgAhlAFAAJECACGsAQEAjQIAIa0BAQCNAgAhrgEBAI0CACGvAQEAjQIAIbABAQCNAgAhsQEBAI0CACGyAQEAjQIAIbMBAgCgAgAhtAECAKACACG1ARAArwIAIbYBAADJAgAgtwEAAMoCACACAAAAAwAgFAAAbwAgAgAAAAMAIBQAAG8AIAMAAAAFACAbAABoACAcAABtACABAAAABQAgAQAAAAMAIAUMAACDAwAgIQAAhgMAICIAAIUDACAzAACEAwAgNAAAhwMAIBOHAQAA6AEAMIgBAAB2ABCJAQAA6AEAMIoBAQC_AQAhkgEAAOoBuQEikwFAAMMBACGUAUAAwwEAIawBAQC_AQAhrQEBAL8BACGuAQEAvwEAIa8BAQC_AQAhsAEBAL8BACGxAQEAvwEAIbIBAQC_AQAhswECANsBACG0AQIA2wEAIbUBEADfAQAhtgEAAOkBACC3AQAA6QEAIAMAAAADACABAAB1ADAgAAB2ACADAAAAAwAgAQAABAAwAgAABQAgAQAAAAwAIAEAAAAMACADAAAACgAgAQAACwAwAgAADAAgAwAAAAoAIAEAAAsAMAIAAAwAIAMAAAAKACABAAALADACAAAMACANBgAA5QIAIAcAAL0CACAJAAC-AgAgigEBAAAAAZIBAAAAqwECkwFAAAAAAZQBQAAAAAGjAQEAAAABpAEBAAAAAacBQAAAAAGoAQIAAAABqQEQAAAAAasBQAAAAAEBFAAAfgAgCooBAQAAAAGSAQAAAKsBApMBQAAAAAGUAUAAAAABowEBAAAAAaQBAQAAAAGnAUAAAAABqAECAAAAAakBEAAAAAGrAUAAAAABARQAAIABADABFAAAgAEAMA0GAADjAgAgBwAAswIAIAkAALQCACCKAQEAjQIAIZIBAACwAqsBIpMBQACRAgAhlAFAAJECACGjAQEAjQIAIaQBAQCNAgAhpwFAAJECACGoAQIAoAIAIakBEACvAgAhqwFAALECACECAAAADAAgFAAAgwEAIAqKAQEAjQIAIZIBAACwAqsBIpMBQACRAgAhlAFAAJECACGjAQEAjQIAIaQBAQCNAgAhpwFAAJECACGoAQIAoAIAIakBEACvAgAhqwFAALECACECAAAACgAgFAAAhQEAIAIAAAAKACAUAACFAQAgAwAAAAwAIBsAAH4AIBwAAIMBACABAAAADAAgAQAAAAoAIAYMAAD-AgAgIQAAgQMAICIAAIADACAzAAD_AgAgNAAAggMAIKsBAACJAgAgDYcBAADeAQAwiAEAAIwBABCJAQAA3gEAMIoBAQC_AQAhkgEAAOABqwEikwFAAMMBACGUAUAAwwEAIaMBAQC_AQAhpAEBAL8BACGnAUAAwwEAIagBAgDbAQAhqQEQAN8BACGrAUAA4QEAIQMAAAAKACABAACLAQAwIAAAjAEAIAMAAAAKACABAAALADACAAAMACABAAAAEgAgAQAAABIAIAMAAAAQACABAAARADACAAASACADAAAAEAAgAQAAEQAwAgAAEgAgAwAAABAAIAEAABEAMAIAABIAIAkGAADaAgAgBwAApAIAIIoBAQAAAAGTAUAAAAABlAFAAAAAAaMBAQAAAAGkAQEAAAABpQECAAAAAaYBAQAAAAEBFAAAlAEAIAeKAQEAAAABkwFAAAAAAZQBQAAAAAGjAQEAAAABpAEBAAAAAaUBAgAAAAGmAQEAAAABARQAAJYBADABFAAAlgEAMAkGAADYAgAgBwAAogIAIIoBAQCNAgAhkwFAAJECACGUAUAAkQIAIaMBAQCNAgAhpAEBAI0CACGlAQIAoAIAIaYBAQCOAgAhAgAAABIAIBQAAJkBACAHigEBAI0CACGTAUAAkQIAIZQBQACRAgAhowEBAI0CACGkAQEAjQIAIaUBAgCgAgAhpgEBAI4CACECAAAAEAAgFAAAmwEAIAIAAAAQACAUAACbAQAgAwAAABIAIBsAAJQBACAcAACZAQAgAQAAABIAIAEAAAAQACAGDAAA-QIAICEAAPwCACAiAAD7AgAgMwAA-gIAIDQAAP0CACCmAQAAiQIAIAqHAQAA2gEAMIgBAACiAQAQiQEAANoBADCKAQEAvwEAIZMBQADDAQAhlAFAAMMBACGjAQEAvwEAIaQBAQC_AQAhpQECANsBACGmAQEAwAEAIQMAAAAQACABAAChAQAwIAAAogEAIAMAAAAQACABAAARADACAAASACAQBAAA1gEAIAUAANcBACAKAADYAQAgCwAA2QEAIIcBAADQAQAwiAEAAKgBABCJAQAA0AEAMIoBAQAAAAGLAQEA0QEAIYwBAQAAAAGNAQEA0QEAIY4BAQDSAQAhkAEAANMBkAEikgEAANQBkgEikwFAANUBACGUAUAA1QEAIQEAAAClAQAgAQAAAKUBACAQBAAA1gEAIAUAANcBACAKAADYAQAgCwAA2QEAIIcBAADQAQAwiAEAAKgBABCJAQAA0AEAMIoBAQDRAQAhiwEBANEBACGMAQEA0QEAIY0BAQDRAQAhjgEBANIBACGQAQAA0wGQASKSAQAA1AGSASKTAUAA1QEAIZQBQADVAQAhBQQAAPUCACAFAAD2AgAgCgAA9wIAIAsAAPgCACCOAQAAiQIAIAMAAACoAQAgAQAAqQEAMAIAAKUBACADAAAAqAEAIAEAAKkBADACAAClAQAgAwAAAKgBACABAACpAQAwAgAApQEAIA0EAADxAgAgBQAA8gIAIAoAAPMCACALAAD0AgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQEBAAAAAY4BAQAAAAGQAQAAAJABApIBAAAAkgECkwFAAAAAAZQBQAAAAAEBFAAArQEAIAmKAQEAAAABiwEBAAAAAYwBAQAAAAGNAQEAAAABjgEBAAAAAZABAAAAkAECkgEAAACSAQKTAUAAAAABlAFAAAAAAQEUAACvAQAwARQAAK8BADANBAAAkgIAIAUAAJMCACAKAACUAgAgCwAAlQIAIIoBAQCNAgAhiwEBAI0CACGMAQEAjQIAIY0BAQCNAgAhjgEBAI4CACGQAQAAjwKQASKSAQAAkAKSASKTAUAAkQIAIZQBQACRAgAhAgAAAKUBACAUAACyAQAgCYoBAQCNAgAhiwEBAI0CACGMAQEAjQIAIY0BAQCNAgAhjgEBAI4CACGQAQAAjwKQASKSAQAAkAKSASKTAUAAkQIAIZQBQACRAgAhAgAAAKgBACAUAAC0AQAgAgAAAKgBACAUAAC0AQAgAwAAAKUBACAbAACtAQAgHAAAsgEAIAEAAAClAQAgAQAAAKgBACAEDAAAigIAICEAAIwCACAiAACLAgAgjgEAAIkCACAMhwEAAL4BADCIAQAAuwEAEIkBAAC-AQAwigEBAL8BACGLAQEAvwEAIYwBAQC_AQAhjQEBAL8BACGOAQEAwAEAIZABAADBAZABIpIBAADCAZIBIpMBQADDAQAhlAFAAMMBACEDAAAAqAEAIAEAALoBADAgAAC7AQAgAwAAAKgBACABAACpAQAwAgAApQEAIAyHAQAAvgEAMIgBAAC7AQAQiQEAAL4BADCKAQEAvwEAIYsBAQC_AQAhjAEBAL8BACGNAQEAvwEAIY4BAQDAAQAhkAEAAMEBkAEikgEAAMIBkgEikwFAAMMBACGUAUAAwwEAIQ4MAADFAQAgIQAAzwEAICIAAM8BACCVAQEAAAABlgEBAAAABJcBAQAAAASYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAM4BACGdAQEAAAABngEBAAAAAZ8BAQAAAAEODAAAzAEAICEAAM0BACAiAADNAQAglQEBAAAAAZYBAQAAAAWXAQEAAAAFmAEBAAAAAZkBAQAAAAGaAQEAAAABmwEBAAAAAZwBAQDLAQAhnQEBAAAAAZ4BAQAAAAGfAQEAAAABBwwAAMUBACAhAADKAQAgIgAAygEAIJUBAAAAkAEClgEAAACQAQiXAQAAAJABCJwBAADJAZABIgcMAADFAQAgIQAAyAEAICIAAMgBACCVAQAAAJIBApYBAAAAkgEIlwEAAACSAQicAQAAxwGSASILDAAAxQEAICEAAMYBACAiAADGAQAglQFAAAAAAZYBQAAAAASXAUAAAAAEmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQADEAQAhCwwAAMUBACAhAADGAQAgIgAAxgEAIJUBQAAAAAGWAUAAAAAElwFAAAAABJgBQAAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGcAUAAxAEAIQiVAQIAAAABlgECAAAABJcBAgAAAASYAQIAAAABmQECAAAAAZoBAgAAAAGbAQIAAAABnAECAMUBACEIlQFAAAAAAZYBQAAAAASXAUAAAAAEmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQADGAQAhBwwAAMUBACAhAADIAQAgIgAAyAEAIJUBAAAAkgEClgEAAACSAQiXAQAAAJIBCJwBAADHAZIBIgSVAQAAAJIBApYBAAAAkgEIlwEAAACSAQicAQAAyAGSASIHDAAAxQEAICEAAMoBACAiAADKAQAglQEAAACQAQKWAQAAAJABCJcBAAAAkAEInAEAAMkBkAEiBJUBAAAAkAEClgEAAACQAQiXAQAAAJABCJwBAADKAZABIg4MAADMAQAgIQAAzQEAICIAAM0BACCVAQEAAAABlgEBAAAABZcBAQAAAAWYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAMsBACGdAQEAAAABngEBAAAAAZ8BAQAAAAEIlQECAAAAAZYBAgAAAAWXAQIAAAAFmAECAAAAAZkBAgAAAAGaAQIAAAABmwECAAAAAZwBAgDMAQAhC5UBAQAAAAGWAQEAAAAFlwEBAAAABZgBAQAAAAGZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAzQEAIZ0BAQAAAAGeAQEAAAABnwEBAAAAAQ4MAADFAQAgIQAAzwEAICIAAM8BACCVAQEAAAABlgEBAAAABJcBAQAAAASYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAM4BACGdAQEAAAABngEBAAAAAZ8BAQAAAAELlQEBAAAAAZYBAQAAAASXAQEAAAAEmAEBAAAAAZkBAQAAAAGaAQEAAAABmwEBAAAAAZwBAQDPAQAhnQEBAAAAAZ4BAQAAAAGfAQEAAAABEAQAANYBACAFAADXAQAgCgAA2AEAIAsAANkBACCHAQAA0AEAMIgBAACoAQAQiQEAANABADCKAQEA0QEAIYsBAQDRAQAhjAEBANEBACGNAQEA0QEAIY4BAQDSAQAhkAEAANMBkAEikgEAANQBkgEikwFAANUBACGUAUAA1QEAIQuVAQEAAAABlgEBAAAABJcBAQAAAASYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAM8BACGdAQEAAAABngEBAAAAAZ8BAQAAAAELlQEBAAAAAZYBAQAAAAWXAQEAAAAFmAEBAAAAAZkBAQAAAAGaAQEAAAABmwEBAAAAAZwBAQDNAQAhnQEBAAAAAZ4BAQAAAAGfAQEAAAABBJUBAAAAkAEClgEAAACQAQiXAQAAAJABCJwBAADKAZABIgSVAQAAAJIBApYBAAAAkgEIlwEAAACSAQicAQAAyAGSASIIlQFAAAAAAZYBQAAAAASXAUAAAAAEmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQADGAQAhDAMAAO8BACCHAQAA7gEAMIgBAAAHABCJAQAA7gEAMIoBAQDRAQAhkwFAANUBACGUAUAA1QEAIbwBAQDSAQAhvQEBANIBACG-AQEA0QEAIcgBAAAHACDJAQAABwAgA6ABAAADACChAQAAAwAgogEAAAMAIAOgAQAACgAgoQEAAAoAIKIBAAAKACADoAEAABAAIKEBAAAQACCiAQAAEAAgCocBAADaAQAwiAEAAKIBABCJAQAA2gEAMIoBAQC_AQAhkwFAAMMBACGUAUAAwwEAIaMBAQC_AQAhpAEBAL8BACGlAQIA2wEAIaYBAQDAAQAhDQwAAMUBACAhAADFAQAgIgAAxQEAIDMAAN0BACA0AADFAQAglQECAAAAAZYBAgAAAASXAQIAAAAEmAECAAAAAZkBAgAAAAGaAQIAAAABmwECAAAAAZwBAgDcAQAhDQwAAMUBACAhAADFAQAgIgAAxQEAIDMAAN0BACA0AADFAQAglQECAAAAAZYBAgAAAASXAQIAAAAEmAECAAAAAZkBAgAAAAGaAQIAAAABmwECAAAAAZwBAgDcAQAhCJUBCAAAAAGWAQgAAAAElwEIAAAABJgBCAAAAAGZAQgAAAABmgEIAAAAAZsBCAAAAAGcAQgA3QEAIQ2HAQAA3gEAMIgBAACMAQAQiQEAAN4BADCKAQEAvwEAIZIBAADgAasBIpMBQADDAQAhlAFAAMMBACGjAQEAvwEAIaQBAQC_AQAhpwFAAMMBACGoAQIA2wEAIakBEADfAQAhqwFAAOEBACENDAAAxQEAICEAAOcBACAiAADnAQAgMwAA5wEAIDQAAOcBACCVARAAAAABlgEQAAAABJcBEAAAAASYARAAAAABmQEQAAAAAZoBEAAAAAGbARAAAAABnAEQAOYBACEHDAAAxQEAICEAAOUBACAiAADlAQAglQEAAACrAQKWAQAAAKsBCJcBAAAAqwEInAEAAOQBqwEiCwwAAMwBACAhAADjAQAgIgAA4wEAIJUBQAAAAAGWAUAAAAAFlwFAAAAABZgBQAAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGcAUAA4gEAIQsMAADMAQAgIQAA4wEAICIAAOMBACCVAUAAAAABlgFAAAAABZcBQAAAAAWYAUAAAAABmQFAAAAAAZoBQAAAAAGbAUAAAAABnAFAAOIBACEIlQFAAAAAAZYBQAAAAAWXAUAAAAAFmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQADjAQAhBwwAAMUBACAhAADlAQAgIgAA5QEAIJUBAAAAqwEClgEAAACrAQiXAQAAAKsBCJwBAADkAasBIgSVAQAAAKsBApYBAAAAqwEIlwEAAACrAQicAQAA5QGrASINDAAAxQEAICEAAOcBACAiAADnAQAgMwAA5wEAIDQAAOcBACCVARAAAAABlgEQAAAABJcBEAAAAASYARAAAAABmQEQAAAAAZoBEAAAAAGbARAAAAABnAEQAOYBACEIlQEQAAAAAZYBEAAAAASXARAAAAAEmAEQAAAAAZkBEAAAAAGaARAAAAABmwEQAAAAAZwBEADnAQAhE4cBAADoAQAwiAEAAHYAEIkBAADoAQAwigEBAL8BACGSAQAA6gG5ASKTAUAAwwEAIZQBQADDAQAhrAEBAL8BACGtAQEAvwEAIa4BAQC_AQAhrwEBAL8BACGwAQEAvwEAIbEBAQC_AQAhsgEBAL8BACGzAQIA2wEAIbQBAgDbAQAhtQEQAN8BACG2AQAA6QEAILcBAADpAQAgBJUBAQAAAAW5AQEAAAABugEBAAAABLsBAQAAAAQHDAAAxQEAICEAAOwBACAiAADsAQAglQEAAAC5AQKWAQAAALkBCJcBAAAAuQEInAEAAOsBuQEiBwwAAMUBACAhAADsAQAgIgAA7AEAIJUBAAAAuQEClgEAAAC5AQiXAQAAALkBCJwBAADrAbkBIgSVAQAAALkBApYBAAAAuQEIlwEAAAC5AQicAQAA7AG5ASIJhwEAAO0BADCIAQAAYAAQiQEAAO0BADCKAQEAvwEAIZMBQADDAQAhlAFAAMMBACG8AQEAwAEAIb0BAQDAAQAhvgEBAL8BACEKAwAA7wEAIIcBAADuAQAwiAEAAAcAEIkBAADuAQAwigEBANEBACGTAUAA1QEAIZQBQADVAQAhvAEBANIBACG9AQEA0gEAIb4BAQDRAQAhEgQAANYBACAFAADXAQAgCgAA2AEAIAsAANkBACCHAQAA0AEAMIgBAACoAQAQiQEAANABADCKAQEA0QEAIYsBAQDRAQAhjAEBANEBACGNAQEA0QEAIY4BAQDSAQAhkAEAANMBkAEikgEAANQBkgEikwFAANUBACGUAUAA1QEAIcgBAACoAQAgyQEAAKgBACANhwEAAPABADCIAQAASAAQiQEAAPABADCKAQEAvwEAIZIBAADyAcYBIpMBQADDAQAhlAFAAMMBACG_AQEAvwEAIcABAQC_AQAhwQEQAN8BACHDAQAA8QHDASLEAQEAwAEAIcYBQADhAQAhBwwAAMUBACAhAAD2AQAgIgAA9gEAIJUBAAAAwwEClgEAAADDAQiXAQAAAMMBCJwBAAD1AcMBIgcMAADFAQAgIQAA9AEAICIAAPQBACCVAQAAAMYBApYBAAAAxgEIlwEAAADGAQicAQAA8wHGASIHDAAAxQEAICEAAPQBACAiAAD0AQAglQEAAADGAQKWAQAAAMYBCJcBAAAAxgEInAEAAPMBxgEiBJUBAAAAxgEClgEAAADGAQiXAQAAAMYBCJwBAAD0AcYBIgcMAADFAQAgIQAA9gEAICIAAPYBACCVAQAAAMMBApYBAAAAwwEIlwEAAADDAQicAQAA9QHDASIElQEAAADDAQKWAQAAAMMBCJcBAAAAwwEInAEAAPYBwwEiDggAAPwBACCHAQAA9wEAMIgBAAAOABCJAQAA9wEAMIoBAQDRAQAhkgEAAPoBxgEikwFAANUBACGUAUAA1QEAIb8BAQDRAQAhwAEBANEBACHBARAA-AEAIcMBAAD5AcMBIsQBAQDSAQAhxgFAAPsBACEIlQEQAAAAAZYBEAAAAASXARAAAAAEmAEQAAAAAZkBEAAAAAGaARAAAAABmwEQAAAAAZwBEADnAQAhBJUBAAAAwwEClgEAAADDAQiXAQAAAMMBCJwBAAD2AcMBIgSVAQAAAMYBApYBAAAAxgEIlwEAAADGAQicAQAA9AHGASIIlQFAAAAAAZYBQAAAAAWXAUAAAAAFmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQADjAQAhEgYAAO8BACAHAACCAgAgCQAAhQIAIIcBAACDAgAwiAEAAAoAEIkBAACDAgAwigEBANEBACGSAQAAhAKrASKTAUAA1QEAIZQBQADVAQAhowEBANEBACGkAQEA0QEAIacBQADVAQAhqAECAIECACGpARAA-AEAIasBQAD7AQAhyAEAAAoAIMkBAAAKACAIhwEAAP0BADCIAQAAMAAQiQEAAP0BADCKAQEAvwEAIYsBAQC_AQAhkwFAAMMBACGUAUAAwwEAIa8BAQDAAQAhCQUAANcBACCHAQAA_gEAMIgBAAAdABCJAQAA_gEAMIoBAQDRAQAhiwEBANEBACGTAUAA1QEAIZQBQADVAQAhrwEBANIBACECowEBAAAAAaQBAQAAAAEMBgAA7wEAIAcAAIICACCHAQAAgAIAMIgBAAAQABCJAQAAgAIAMIoBAQDRAQAhkwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGlAQIAgQIAIaYBAQDSAQAhCJUBAgAAAAGWAQIAAAAElwECAAAABJgBAgAAAAGZAQIAAAABmgECAAAAAZsBAgAAAAGcAQIAxQEAIRkKAADYAQAgCwAA2QEAIA0AAO8BACAOAACIAgAghwEAAIYCADCIAQAAAwAQiQEAAIYCADCKAQEA0QEAIZIBAACHArkBIpMBQADVAQAhlAFAANUBACGsAQEA0QEAIa0BAQDRAQAhrgEBANEBACGvAQEA0QEAIbABAQDRAQAhsQEBANEBACGyAQEA0QEAIbMBAgCBAgAhtAECAIECACG1ARAA-AEAIbYBAADpAQAgtwEAAOkBACDIAQAAAwAgyQEAAAMAIBAGAADvAQAgBwAAggIAIAkAAIUCACCHAQAAgwIAMIgBAAAKABCJAQAAgwIAMIoBAQDRAQAhkgEAAIQCqwEikwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGnAUAA1QEAIagBAgCBAgAhqQEQAPgBACGrAUAA-wEAIQSVAQAAAKsBApYBAAAAqwEIlwEAAACrAQicAQAA5QGrASIQCAAA_AEAIIcBAAD3AQAwiAEAAA4AEIkBAAD3AQAwigEBANEBACGSAQAA-gHGASKTAUAA1QEAIZQBQADVAQAhvwEBANEBACHAAQEA0QEAIcEBEAD4AQAhwwEAAPkBwwEixAEBANIBACHGAUAA-wEAIcgBAAAOACDJAQAADgAgFwoAANgBACALAADZAQAgDQAA7wEAIA4AAIgCACCHAQAAhgIAMIgBAAADABCJAQAAhgIAMIoBAQDRAQAhkgEAAIcCuQEikwFAANUBACGUAUAA1QEAIawBAQDRAQAhrQEBANEBACGuAQEA0QEAIa8BAQDRAQAhsAEBANEBACGxAQEA0QEAIbIBAQDRAQAhswECAIECACG0AQIAgQIAIbUBEAD4AQAhtgEAAOkBACC3AQAA6QEAIASVAQAAALkBApYBAAAAuQEIlwEAAAC5AQicAQAA7AG5ASILBQAA1wEAIIcBAAD-AQAwiAEAAB0AEIkBAAD-AQAwigEBANEBACGLAQEA0QEAIZMBQADVAQAhlAFAANUBACGvAQEA0gEAIcgBAAAdACDJAQAAHQAgAAAAAAHNAQEAAAABAc0BAQAAAAEBzQEAAACQAQIBzQEAAACSAQIBzQFAAAAAAQcbAADsAgAgHAAA7wIAIMoBAADtAgAgywEAAO4CACDOAQAABwAgzwEAAAcAINABAABLACALGwAAvwIAMBwAAMQCADDKAQAAwAIAMMsBAADBAgAwzAEAAMICACDNAQAAwwIAMM4BAADDAgAwzwEAAMMCADDQAQAAwwIAMNEBAADFAgAw0gEAAMYCADALGwAApQIAMBwAAKoCADDKAQAApgIAMMsBAACnAgAwzAEAAKgCACDNAQAAqQIAMM4BAACpAgAwzwEAAKkCADDQAQAAqQIAMNEBAACrAgAw0gEAAKwCADALGwAAlgIAMBwAAJsCADDKAQAAlwIAMMsBAACYAgAwzAEAAJkCACDNAQAAmgIAMM4BAACaAgAwzwEAAJoCADDQAQAAmgIAMNEBAACcAgAw0gEAAJ0CADAHBwAApAIAIIoBAQAAAAGTAUAAAAABlAFAAAAAAaQBAQAAAAGlAQIAAAABpgEBAAAAAQIAAAASACAbAACjAgAgAwAAABIAIBsAAKMCACAcAAChAgAgARQAANYDADANBgAA7wEAIAcAAIICACCHAQAAgAIAMIgBAAAQABCJAQAAgAIAMIoBAQAAAAGTAUAA1QEAIZQBQADVAQAhowEBANEBACGkAQEA0QEAIaUBAgCBAgAhpgEBANIBACHHAQAA_wEAIAIAAAASACAUAAChAgAgAgAAAJ4CACAUAACfAgAgCocBAACdAgAwiAEAAJ4CABCJAQAAnQIAMIoBAQDRAQAhkwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGlAQIAgQIAIaYBAQDSAQAhCocBAACdAgAwiAEAAJ4CABCJAQAAnQIAMIoBAQDRAQAhkwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGlAQIAgQIAIaYBAQDSAQAhBooBAQCNAgAhkwFAAJECACGUAUAAkQIAIaQBAQCNAgAhpQECAKACACGmAQEAjgIAIQXNAQIAAAAB1AECAAAAAdUBAgAAAAHWAQIAAAAB1wECAAAAAQcHAACiAgAgigEBAI0CACGTAUAAkQIAIZQBQACRAgAhpAEBAI0CACGlAQIAoAIAIaYBAQCOAgAhBRsAANEDACAcAADUAwAgygEAANIDACDLAQAA0wMAINABAAAFACAHBwAApAIAIIoBAQAAAAGTAUAAAAABlAFAAAAAAaQBAQAAAAGlAQIAAAABpgEBAAAAAQMbAADRAwAgygEAANIDACDQAQAABQAgCwcAAL0CACAJAAC-AgAgigEBAAAAAZIBAAAAqwECkwFAAAAAAZQBQAAAAAGkAQEAAAABpwFAAAAAAagBAgAAAAGpARAAAAABqwFAAAAAAQIAAAAMACAbAAC8AgAgAwAAAAwAIBsAALwCACAcAACyAgAgARQAANADADAQBgAA7wEAIAcAAIICACAJAACFAgAghwEAAIMCADCIAQAACgAQiQEAAIMCADCKAQEAAAABkgEAAIQCqwEikwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGnAUAA1QEAIagBAgCBAgAhqQEQAPgBACGrAUAA-wEAIQIAAAAMACAUAACyAgAgAgAAAK0CACAUAACuAgAgDYcBAACsAgAwiAEAAK0CABCJAQAArAIAMIoBAQDRAQAhkgEAAIQCqwEikwFAANUBACGUAUAA1QEAIaMBAQDRAQAhpAEBANEBACGnAUAA1QEAIagBAgCBAgAhqQEQAPgBACGrAUAA-wEAIQ2HAQAArAIAMIgBAACtAgAQiQEAAKwCADCKAQEA0QEAIZIBAACEAqsBIpMBQADVAQAhlAFAANUBACGjAQEA0QEAIaQBAQDRAQAhpwFAANUBACGoAQIAgQIAIakBEAD4AQAhqwFAAPsBACEJigEBAI0CACGSAQAAsAKrASKTAUAAkQIAIZQBQACRAgAhpAEBAI0CACGnAUAAkQIAIagBAgCgAgAhqQEQAK8CACGrAUAAsQIAIQXNARAAAAAB1AEQAAAAAdUBEAAAAAHWARAAAAAB1wEQAAAAAQHNAQAAAKsBAgHNAUAAAAABCwcAALMCACAJAAC0AgAgigEBAI0CACGSAQAAsAKrASKTAUAAkQIAIZQBQACRAgAhpAEBAI0CACGnAUAAkQIAIagBAgCgAgAhqQEQAK8CACGrAUAAsQIAIQUbAADLAwAgHAAAzgMAIMoBAADMAwAgywEAAM0DACDQAQAABQAgBxsAALUCACAcAAC4AgAgygEAALYCACDLAQAAtwIAIM4BAAAOACDPAQAADgAg0AEAADMAIAmKAQEAAAABkgEAAADGAQKTAUAAAAABlAFAAAAAAcABAQAAAAHBARAAAAABwwEAAADDAQLEAQEAAAABxgFAAAAAAQIAAAAzACAbAAC1AgAgAwAAAA4AIBsAALUCACAcAAC5AgAgCwAAAA4AIBQAALkCACCKAQEAjQIAIZIBAAC7AsYBIpMBQACRAgAhlAFAAJECACHAAQEAjQIAIcEBEACvAgAhwwEAALoCwwEixAEBAI4CACHGAUAAsQIAIQmKAQEAjQIAIZIBAAC7AsYBIpMBQACRAgAhlAFAAJECACHAAQEAjQIAIcEBEACvAgAhwwEAALoCwwEixAEBAI4CACHGAUAAsQIAIQHNAQAAAMMBAgHNAQAAAMYBAgsHAAC9AgAgCQAAvgIAIIoBAQAAAAGSAQAAAKsBApMBQAAAAAGUAUAAAAABpAEBAAAAAacBQAAAAAGoAQIAAAABqQEQAAAAAasBQAAAAAEDGwAAywMAIMoBAADMAwAg0AEAAAUAIAMbAAC1AgAgygEAALYCACDQAQAAMwAgEgoAAOoCACALAADrAgAgDgAA6QIAIIoBAQAAAAGSAQAAALkBApMBQAAAAAGUAUAAAAABrQEBAAAAAa4BAQAAAAGvAQEAAAABsAEBAAAAAbEBAQAAAAGyAQEAAAABswECAAAAAbQBAgAAAAG1ARAAAAABtgEAAOcCACC3AQAA6AIAIAIAAAAFACAbAADmAgAgAwAAAAUAIBsAAOYCACAcAADMAgAgARQAAMoDADAXCgAA2AEAIAsAANkBACANAADvAQAgDgAAiAIAIIcBAACGAgAwiAEAAAMAEIkBAACGAgAwigEBAAAAAZIBAACHArkBIpMBQADVAQAhlAFAANUBACGsAQEA0QEAIa0BAQDRAQAhrgEBANEBACGvAQEA0QEAIbABAQDRAQAhsQEBANEBACGyAQEA0QEAIbMBAgCBAgAhtAECAIECACG1ARAA-AEAIbYBAADpAQAgtwEAAOkBACACAAAABQAgFAAAzAIAIAIAAADHAgAgFAAAyAIAIBOHAQAAxgIAMIgBAADHAgAQiQEAAMYCADCKAQEA0QEAIZIBAACHArkBIpMBQADVAQAhlAFAANUBACGsAQEA0QEAIa0BAQDRAQAhrgEBANEBACGvAQEA0QEAIbABAQDRAQAhsQEBANEBACGyAQEA0QEAIbMBAgCBAgAhtAECAIECACG1ARAA-AEAIbYBAADpAQAgtwEAAOkBACAThwEAAMYCADCIAQAAxwIAEIkBAADGAgAwigEBANEBACGSAQAAhwK5ASKTAUAA1QEAIZQBQADVAQAhrAEBANEBACGtAQEA0QEAIa4BAQDRAQAhrwEBANEBACGwAQEA0QEAIbEBAQDRAQAhsgEBANEBACGzAQIAgQIAIbQBAgCBAgAhtQEQAPgBACG2AQAA6QEAILcBAADpAQAgD4oBAQCNAgAhkgEAAMsCuQEikwFAAJECACGUAUAAkQIAIa0BAQCNAgAhrgEBAI0CACGvAQEAjQIAIbABAQCNAgAhsQEBAI0CACGyAQEAjQIAIbMBAgCgAgAhtAECAKACACG1ARAArwIAIbYBAADJAgAgtwEAAMoCACACzQEBAAAABNMBAQAAAAUCzQEBAAAABNMBAQAAAAUBzQEAAAC5AQISCgAAzgIAIAsAAM8CACAOAADNAgAgigEBAI0CACGSAQAAywK5ASKTAUAAkQIAIZQBQACRAgAhrQEBAI0CACGuAQEAjQIAIa8BAQCNAgAhsAEBAI0CACGxAQEAjQIAIbIBAQCNAgAhswECAKACACG0AQIAoAIAIbUBEACvAgAhtgEAAMkCACC3AQAAygIAIAUbAAC5AwAgHAAAyAMAIMoBAAC6AwAgywEAAMcDACDQAQAAAQAgCxsAANsCADAcAADfAgAwygEAANwCADDLAQAA3QIAMMwBAADeAgAgzQEAAKkCADDOAQAAqQIAMM8BAACpAgAw0AEAAKkCADDRAQAA4AIAMNIBAACsAgAwCxsAANACADAcAADUAgAwygEAANECADDLAQAA0gIAMMwBAADTAgAgzQEAAJoCADDOAQAAmgIAMM8BAACaAgAw0AEAAJoCADDRAQAA1QIAMNIBAACdAgAwBwYAANoCACCKAQEAAAABkwFAAAAAAZQBQAAAAAGjAQEAAAABpQECAAAAAaYBAQAAAAECAAAAEgAgGwAA2QIAIAMAAAASACAbAADZAgAgHAAA1wIAIAEUAADGAwAwAgAAABIAIBQAANcCACACAAAAngIAIBQAANYCACAGigEBAI0CACGTAUAAkQIAIZQBQACRAgAhowEBAI0CACGlAQIAoAIAIaYBAQCOAgAhBwYAANgCACCKAQEAjQIAIZMBQACRAgAhlAFAAJECACGjAQEAjQIAIaUBAgCgAgAhpgEBAI4CACEFGwAAwQMAIBwAAMQDACDKAQAAwgMAIMsBAADDAwAg0AEAAKUBACAHBgAA2gIAIIoBAQAAAAGTAUAAAAABlAFAAAAAAaMBAQAAAAGlAQIAAAABpgEBAAAAAQMbAADBAwAgygEAAMIDACDQAQAApQEAIAsGAADlAgAgCQAAvgIAIIoBAQAAAAGSAQAAAKsBApMBQAAAAAGUAUAAAAABowEBAAAAAacBQAAAAAGoAQIAAAABqQEQAAAAAasBQAAAAAECAAAADAAgGwAA5AIAIAMAAAAMACAbAADkAgAgHAAA4gIAIAEUAADAAwAwAgAAAAwAIBQAAOICACACAAAArQIAIBQAAOECACAJigEBAI0CACGSAQAAsAKrASKTAUAAkQIAIZQBQACRAgAhowEBAI0CACGnAUAAkQIAIagBAgCgAgAhqQEQAK8CACGrAUAAsQIAIQsGAADjAgAgCQAAtAIAIIoBAQCNAgAhkgEAALACqwEikwFAAJECACGUAUAAkQIAIaMBAQCNAgAhpwFAAJECACGoAQIAoAIAIakBEACvAgAhqwFAALECACEFGwAAuwMAIBwAAL4DACDKAQAAvAMAIMsBAAC9AwAg0AEAAKUBACALBgAA5QIAIAkAAL4CACCKAQEAAAABkgEAAACrAQKTAUAAAAABlAFAAAAAAaMBAQAAAAGnAUAAAAABqAECAAAAAakBEAAAAAGrAUAAAAABAxsAALsDACDKAQAAvAMAINABAAClAQAgEgoAAOoCACALAADrAgAgDgAA6QIAIIoBAQAAAAGSAQAAALkBApMBQAAAAAGUAUAAAAABrQEBAAAAAa4BAQAAAAGvAQEAAAABsAEBAAAAAbEBAQAAAAGyAQEAAAABswECAAAAAbQBAgAAAAG1ARAAAAABtgEAAOcCACC3AQAA6AIAIAHNAQEAAAAEAc0BAQAAAAQDGwAAuQMAIMoBAAC6AwAg0AEAAAEAIAQbAADbAgAwygEAANwCADDMAQAA3gIAINABAACpAgAwBBsAANACADDKAQAA0QIAMMwBAADTAgAg0AEAAJoCADAFigEBAAAAAZMBQAAAAAGUAUAAAAABvAEBAAAAAb0BAQAAAAECAAAASwAgGwAA7AIAIAMAAAAHACAbAADsAgAgHAAA8AIAIAcAAAAHACAUAADwAgAgigEBAI0CACGTAUAAkQIAIZQBQACRAgAhvAEBAI4CACG9AQEAjgIAIQWKAQEAjQIAIZMBQACRAgAhlAFAAJECACG8AQEAjgIAIb0BAQCOAgAhAxsAAOwCACDKAQAA7QIAINABAABLACAEGwAAvwIAMMoBAADAAgAwzAEAAMICACDQAQAAwwIAMAQbAAClAgAwygEAAKYCADDMAQAAqAIAINABAACpAgAwBBsAAJYCADDKAQAAlwIAMMwBAACZAgAg0AEAAJoCADADAwAAjwMAILwBAACJAgAgvQEAAIkCACAAAAAAAAAAAAAAAAAAAAAAAAAFGwAAtAMAIBwAALcDACDKAQAAtQMAIMsBAAC2AwAg0AEAAKUBACADGwAAtAMAIMoBAAC1AwAg0AEAAKUBACAAAAAFGwAArwMAIBwAALIDACDKAQAAsAMAIMsBAACxAwAg0AEAAKUBACADGwAArwMAIMoBAACwAwAg0AEAAKUBACAFBAAA9QIAIAUAAPYCACAKAAD3AgAgCwAA-AIAII4BAACJAgAgAAAAAAAFGwAAqgMAIBwAAK0DACDKAQAAqwMAIMsBAACsAwAg0AEAAAwAIAMbAACqAwAgygEAAKsDACDQAQAADAAgBAYAAI8DACAHAACmAwAgCQAApwMAIKsBAACJAgAgAAAACxsAAJwDADAcAACgAwAwygEAAJ0DADDLAQAAngMAMMwBAACfAwAgzQEAAMMCADDOAQAAwwIAMM8BAADDAgAw0AEAAMMCADDRAQAAoQMAMNIBAADGAgAwEgoAAOoCACALAADrAgAgDQAAiQMAIIoBAQAAAAGSAQAAALkBApMBQAAAAAGUAUAAAAABrAEBAAAAAa4BAQAAAAGvAQEAAAABsAEBAAAAAbEBAQAAAAGyAQEAAAABswECAAAAAbQBAgAAAAG1ARAAAAABtgEAAOcCACC3AQAA6AIAIAIAAAAFACAbAACkAwAgAwAAAAUAIBsAAKQDACAcAACjAwAgARQAAKkDADACAAAABQAgFAAAowMAIAIAAADHAgAgFAAAogMAIA-KAQEAjQIAIZIBAADLArkBIpMBQACRAgAhlAFAAJECACGsAQEAjQIAIa4BAQCNAgAhrwEBAI0CACGwAQEAjQIAIbEBAQCNAgAhsgEBAI0CACGzAQIAoAIAIbQBAgCgAgAhtQEQAK8CACG2AQAAyQIAILcBAADKAgAgEgoAAM4CACALAADPAgAgDQAAiAMAIIoBAQCNAgAhkgEAAMsCuQEikwFAAJECACGUAUAAkQIAIawBAQCNAgAhrgEBAI0CACGvAQEAjQIAIbABAQCNAgAhsQEBAI0CACGyAQEAjQIAIbMBAgCgAgAhtAECAKACACG1ARAArwIAIbYBAADJAgAgtwEAAMoCACASCgAA6gIAIAsAAOsCACANAACJAwAgigEBAAAAAZIBAAAAuQECkwFAAAAAAZQBQAAAAAGsAQEAAAABrgEBAAAAAa8BAQAAAAGwAQEAAAABsQEBAAAAAbIBAQAAAAGzAQIAAAABtAECAAAAAbUBEAAAAAG2AQAA5wIAILcBAADoAgAgBBsAAJwDADDKAQAAnQMAMMwBAACfAwAg0AEAAMMCADAECgAA9wIAIAsAAPgCACANAACPAwAgDgAAqAMAIAMIAACXAwAgxAEAAIkCACDGAQAAiQIAIAIFAAD2AgAgrwEAAIkCACAPigEBAAAAAZIBAAAAuQECkwFAAAAAAZQBQAAAAAGsAQEAAAABrgEBAAAAAa8BAQAAAAGwAQEAAAABsQEBAAAAAbIBAQAAAAGzAQIAAAABtAECAAAAAbUBEAAAAAG2AQAA5wIAILcBAADoAgAgDAYAAOUCACAHAAC9AgAgigEBAAAAAZIBAAAAqwECkwFAAAAAAZQBQAAAAAGjAQEAAAABpAEBAAAAAacBQAAAAAGoAQIAAAABqQEQAAAAAasBQAAAAAECAAAADAAgGwAAqgMAIAMAAAAKACAbAACqAwAgHAAArgMAIA4AAAAKACAGAADjAgAgBwAAswIAIBQAAK4DACCKAQEAjQIAIZIBAACwAqsBIpMBQACRAgAhlAFAAJECACGjAQEAjQIAIaQBAQCNAgAhpwFAAJECACGoAQIAoAIAIakBEACvAgAhqwFAALECACEMBgAA4wIAIAcAALMCACCKAQEAjQIAIZIBAACwAqsBIpMBQACRAgAhlAFAAJECACGjAQEAjQIAIaQBAQCNAgAhpwFAAJECACGoAQIAoAIAIakBEACvAgAhqwFAALECACEMBQAA8gIAIAoAAPMCACALAAD0AgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQEBAAAAAY4BAQAAAAGQAQAAAJABApIBAAAAkgECkwFAAAAAAZQBQAAAAAECAAAApQEAIBsAAK8DACADAAAAqAEAIBsAAK8DACAcAACzAwAgDgAAAKgBACAFAACTAgAgCgAAlAIAIAsAAJUCACAUAACzAwAgigEBAI0CACGLAQEAjQIAIYwBAQCNAgAhjQEBAI0CACGOAQEAjgIAIZABAACPApABIpIBAACQApIBIpMBQACRAgAhlAFAAJECACEMBQAAkwIAIAoAAJQCACALAACVAgAgigEBAI0CACGLAQEAjQIAIYwBAQCNAgAhjQEBAI0CACGOAQEAjgIAIZABAACPApABIpIBAACQApIBIpMBQACRAgAhlAFAAJECACEMBAAA8QIAIAoAAPMCACALAAD0AgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQEBAAAAAY4BAQAAAAGQAQAAAJABApIBAAAAkgECkwFAAAAAAZQBQAAAAAECAAAApQEAIBsAALQDACADAAAAqAEAIBsAALQDACAcAAC4AwAgDgAAAKgBACAEAACSAgAgCgAAlAIAIAsAAJUCACAUAAC4AwAgigEBAI0CACGLAQEAjQIAIYwBAQCNAgAhjQEBAI0CACGOAQEAjgIAIZABAACPApABIpIBAACQApIBIpMBQACRAgAhlAFAAJECACEMBAAAkgIAIAoAAJQCACALAACVAgAgigEBAI0CACGLAQEAjQIAIYwBAQCNAgAhjQEBAI0CACGOAQEAjgIAIZABAACPApABIpIBAACQApIBIpMBQACRAgAhlAFAAJECACEFigEBAAAAAYsBAQAAAAGTAUAAAAABlAFAAAAAAa8BAQAAAAECAAAAAQAgGwAAuQMAIAwEAADxAgAgBQAA8gIAIAsAAPQCACCKAQEAAAABiwEBAAAAAYwBAQAAAAGNAQEAAAABjgEBAAAAAZABAAAAkAECkgEAAACSAQKTAUAAAAABlAFAAAAAAQIAAAClAQAgGwAAuwMAIAMAAACoAQAgGwAAuwMAIBwAAL8DACAOAAAAqAEAIAQAAJICACAFAACTAgAgCwAAlQIAIBQAAL8DACCKAQEAjQIAIYsBAQCNAgAhjAEBAI0CACGNAQEAjQIAIY4BAQCOAgAhkAEAAI8CkAEikgEAAJACkgEikwFAAJECACGUAUAAkQIAIQwEAACSAgAgBQAAkwIAIAsAAJUCACCKAQEAjQIAIYsBAQCNAgAhjAEBAI0CACGNAQEAjQIAIY4BAQCOAgAhkAEAAI8CkAEikgEAAJACkgEikwFAAJECACGUAUAAkQIAIQmKAQEAAAABkgEAAACrAQKTAUAAAAABlAFAAAAAAaMBAQAAAAGnAUAAAAABqAECAAAAAakBEAAAAAGrAUAAAAABDAQAAPECACAFAADyAgAgCgAA8wIAIIoBAQAAAAGLAQEAAAABjAEBAAAAAY0BAQAAAAGOAQEAAAABkAEAAACQAQKSAQAAAJIBApMBQAAAAAGUAUAAAAABAgAAAKUBACAbAADBAwAgAwAAAKgBACAbAADBAwAgHAAAxQMAIA4AAACoAQAgBAAAkgIAIAUAAJMCACAKAACUAgAgFAAAxQMAIIoBAQCNAgAhiwEBAI0CACGMAQEAjQIAIY0BAQCNAgAhjgEBAI4CACGQAQAAjwKQASKSAQAAkAKSASKTAUAAkQIAIZQBQACRAgAhDAQAAJICACAFAACTAgAgCgAAlAIAIIoBAQCNAgAhiwEBAI0CACGMAQEAjQIAIY0BAQCNAgAhjgEBAI4CACGQAQAAjwKQASKSAQAAkAKSASKTAUAAkQIAIZQBQACRAgAhBooBAQAAAAGTAUAAAAABlAFAAAAAAaMBAQAAAAGlAQIAAAABpgEBAAAAAQMAAAAdACAbAAC5AwAgHAAAyQMAIAcAAAAdACAUAADJAwAgigEBAI0CACGLAQEAjQIAIZMBQACRAgAhlAFAAJECACGvAQEAjgIAIQWKAQEAjQIAIYsBAQCNAgAhkwFAAJECACGUAUAAkQIAIa8BAQCOAgAhD4oBAQAAAAGSAQAAALkBApMBQAAAAAGUAUAAAAABrQEBAAAAAa4BAQAAAAGvAQEAAAABsAEBAAAAAbEBAQAAAAGyAQEAAAABswECAAAAAbQBAgAAAAG1ARAAAAABtgEAAOcCACC3AQAA6AIAIBMLAADrAgAgDQAAiQMAIA4AAOkCACCKAQEAAAABkgEAAAC5AQKTAUAAAAABlAFAAAAAAawBAQAAAAGtAQEAAAABrgEBAAAAAa8BAQAAAAGwAQEAAAABsQEBAAAAAbIBAQAAAAGzAQIAAAABtAECAAAAAbUBEAAAAAG2AQAA5wIAILcBAADoAgAgAgAAAAUAIBsAAMsDACADAAAAAwAgGwAAywMAIBwAAM8DACAVAAAAAwAgCwAAzwIAIA0AAIgDACAOAADNAgAgFAAAzwMAIIoBAQCNAgAhkgEAAMsCuQEikwFAAJECACGUAUAAkQIAIawBAQCNAgAhrQEBAI0CACGuAQEAjQIAIa8BAQCNAgAhsAEBAI0CACGxAQEAjQIAIbIBAQCNAgAhswECAKACACG0AQIAoAIAIbUBEACvAgAhtgEAAMkCACC3AQAAygIAIBMLAADPAgAgDQAAiAMAIA4AAM0CACCKAQEAjQIAIZIBAADLArkBIpMBQACRAgAhlAFAAJECACGsAQEAjQIAIa0BAQCNAgAhrgEBAI0CACGvAQEAjQIAIbABAQCNAgAhsQEBAI0CACGyAQEAjQIAIbMBAgCgAgAhtAECAKACACG1ARAArwIAIbYBAADJAgAgtwEAAMoCACAJigEBAAAAAZIBAAAAqwECkwFAAAAAAZQBQAAAAAGkAQEAAAABpwFAAAAAAagBAgAAAAGpARAAAAABqwFAAAAAARMKAADqAgAgDQAAiQMAIA4AAOkCACCKAQEAAAABkgEAAAC5AQKTAUAAAAABlAFAAAAAAawBAQAAAAGtAQEAAAABrgEBAAAAAa8BAQAAAAGwAQEAAAABsQEBAAAAAbIBAQAAAAGzAQIAAAABtAECAAAAAbUBEAAAAAG2AQAA5wIAILcBAADoAgAgAgAAAAUAIBsAANEDACADAAAAAwAgGwAA0QMAIBwAANUDACAVAAAAAwAgCgAAzgIAIA0AAIgDACAOAADNAgAgFAAA1QMAIIoBAQCNAgAhkgEAAMsCuQEikwFAAJECACGUAUAAkQIAIawBAQCNAgAhrQEBAI0CACGuAQEAjQIAIa8BAQCNAgAhsAEBAI0CACGxAQEAjQIAIbIBAQCNAgAhswECAKACACG0AQIAoAIAIbUBEACvAgAhtgEAAMkCACC3AQAAygIAIBMKAADOAgAgDQAAiAMAIA4AAM0CACCKAQEAjQIAIZIBAADLArkBIpMBQACRAgAhlAFAAJECACGsAQEAjQIAIa0BAQCNAgAhrgEBAI0CACGvAQEAjQIAIbABAQCNAgAhsQEBAI0CACGyAQEAjQIAIbMBAgCgAgAhtAECAKACACG1ARAArwIAIbYBAADJAgAgtwEAAMoCACAGigEBAAAAAZMBQAAAAAGUAUAAAAABpAEBAAAAAaUBAgAAAAGmAQEAAAABAgUGAgwACgUKFwULGAcMAAkNAAMOAAEFBAgEBQkCCg0FCxMHDAAIAQMAAwMGAAMHAAIJDwYBCAAFAgYAAwcAAgMFFAAKFQALFgACChkACxoAAQUbAAAAAAMMAA8hABAiABEAAAADDAAPIQAQIgARAQgABQEIAAUFDAAWIQAZIgAaMwAXNAAYAAAAAAAFDAAWIQAZIgAaMwAXNAAYAQMAAwEDAAMDDAAfIQAgIgAhAAAAAwwAHyEAICIAIQINAAMOAAECDQADDgABBQwAJiEAKSIAKjMAJzQAKAAAAAAABQwAJiEAKSIAKjMAJzQAKAIGAAMHAAICBgADBwACBQwALyEAMiIAMzMAMDQAMQAAAAAABQwALyEAMiIAMzMAMDQAMQIGAAMHAAICBgADBwACBQwAOCEAOyIAPDMAOTQAOgAAAAAABQwAOCEAOyIAPDMAOTQAOgAAAwwAQSEAQiIAQwAAAAMMAEEhAEIiAEMPAgEQHAERHwESIAETIQEVIwEWJQsXJgwYKAEZKgsaKw0dLAEeLQEfLgsjMQ4kMhIlNAYmNQYnNwYoOAYpOQYqOwYrPQssPhMtQAYuQgsvQxQwRAYxRQYyRgs1SRU2Shs3TAQ4TQQ5TwQ6UAQ7UQQ8UwQ9VQs-Vhw_WARAWgtBWx1CXARDXQREXgtFYR5GYiJHYwJIZAJJZQJKZgJLZwJMaQJNawtObCNPbgJQcAtRcSRScgJTcwJUdAtVdyVWeCtXeQVYegVZewVafAVbfQVcfwVdgQELXoIBLF-EAQVghgELYYcBLWKIAQVjiQEFZIoBC2WNAS5mjgE0Z48BB2iQAQdpkQEHapIBB2uTAQdslQEHbZcBC26YATVvmgEHcJwBC3GdATZyngEHc58BB3SgAQt1owE3dqQBPXemAQN4pwEDeaoBA3qrAQN7rAEDfK4BA32wAQt-sQE-f7MBA4ABtQELgQG2AT-CAbcBA4MBuAEDhAG5AQuFAbwBQIYBvQFE"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// src/generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AnyNull: () => AnyNull2,
  CategoryScalarFieldEnum: () => CategoryScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  JsonNull: () => JsonNull2,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullsOrder: () => NullsOrder,
  PaymentScalarFieldEnum: () => PaymentScalarFieldEnum,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  ProfileScalarFieldEnum: () => ProfileScalarFieldEnum,
  PropertyScalarFieldEnum: () => PropertyScalarFieldEnum,
  QueryMode: () => QueryMode,
  RentalRequestScalarFieldEnum: () => RentalRequestScalarFieldEnum,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.9.1",
  engine: "e922089b7d7502aff4249d5da3420f6fa55fc6ad"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  Category: "Category",
  Payment: "Payment",
  Profile: "Profile",
  Property: "Property",
  RentalRequest: "RentalRequest",
  Review: "Review",
  User: "User"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var CategoryScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var PaymentScalarFieldEnum = {
  id: "id",
  rentalRequestId: "rentalRequestId",
  transactionId: "transactionId",
  amount: "amount",
  provider: "provider",
  paymentMethod: "paymentMethod",
  status: "status",
  paidAt: "paidAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var ProfileScalarFieldEnum = {
  id: "id",
  profilePhoto: "profilePhoto",
  bio: "bio",
  userId: "userId",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var PropertyScalarFieldEnum = {
  id: "id",
  landlordId: "landlordId",
  categoryId: "categoryId",
  title: "title",
  description: "description",
  address: "address",
  city: "city",
  propertyType: "propertyType",
  bedrooms: "bedrooms",
  bathrooms: "bathrooms",
  rentPrice: "rentPrice",
  amenities: "amenities",
  images: "images",
  status: "status",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var RentalRequestScalarFieldEnum = {
  id: "id",
  tenantId: "tenantId",
  propertyId: "propertyId",
  moveInDate: "moveInDate",
  duration: "duration",
  monthlyRent: "monthlyRent",
  status: "status",
  approvedAt: "approvedAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var ReviewScalarFieldEnum = {
  id: "id",
  tenantId: "tenantId",
  propertyId: "propertyId",
  rating: "rating",
  comment: "comment",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  password: "password",
  phone: "phone",
  role: "role",
  status: "status",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var defineExtension = runtime2.Extensions.defineExtension;

// src/generated/prisma/enums.ts
var UserRole = {
  TENANT: "TENANT",
  LANDLORD: "LANDLORD",
  ADMIN: "ADMIN"
};
var UserStatus = {
  ACTIVE: "ACTIVE",
  BANNED: "BANNED"
};
var PropertyStatus = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  RENTED: "RENTED",
  UNAVAILABLE: "UNAVAILABLE"
};
var RentalRequestStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED"
};
var PaymentProvider = {
  STRIPE: "STRIPE",
  SSLCOMMERZ: "SSLCOMMERZ"
};
var PaymentStatus = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
};

// src/generated/prisma/client.ts
globalThis["__dirname"] = path2.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/auth/service.ts
import bcrypt from "bcryptjs";

// src/utils/jwt.ts
import jwt from "jsonwebtoken";
var createToken = (payload, secret, expiresIn) => {
  const token = jwt.sign(
    payload,
    secret,
    {
      expiresIn
    }
  );
  return token;
};
var verifyToken = (token, secret) => {
  try {
    const verifiedToken = jwt.verify(token, secret);
    return {
      success: true,
      data: verifiedToken
    };
  } catch (error) {
    console.log("Token verification failed:", error);
    return {
      success: false,
      error: error.message
    };
  }
};
var jwtUtils = {
  createToken,
  verifyToken
};

// src/modules/auth/service.ts
var registerUser = async (payload) => {
  const { name, email, password, role, phone, profilePhoto } = payload;
  const isUserExist = await prisma.user.findUnique({
    where: { email }
  });
  const hashedPassword = await bcrypt.hash(password, Number(config_default.bcrypt_salt_rounds));
  const createdUser = await prisma.user.create({
    data: {
      name,
      email,
      password: hashedPassword,
      role,
      phone,
      profile: {
        create: {
          profilePhoto
        }
      }
    }
  });
  const user = await prisma.user.findUnique({
    where: {
      id: createdUser.id,
      email: createdUser.email || email
    },
    omit: {
      password: true
    },
    include: {
      profile: true
    }
  });
  return user;
};
var loginUser = async (payload) => {
  const { email, password } = payload;
  const user = await prisma.user.findUniqueOrThrow({
    where: { email }
  });
  if (user.status === "BANNED") {
    throw new Error("Your account has been banned. Please contact support.");
  }
  const isPasswordMatched = await bcrypt.compare(password, user.password);
  if (!isPasswordMatched) {
    throw new Error("Password is incorrect");
  }
  const jwtPayload = {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role
  };
  const accessToken = jwtUtils.createToken(
    jwtPayload,
    config_default.jwt_access_secret,
    config_default.jwt_access_expires_in
  );
  const refreshToken = jwtUtils.createToken(
    jwtPayload,
    config_default.jwt_refresh_secret,
    config_default.jwt_refresh_expires_in
  );
  const { password: _, ...userWithoutPassword } = user;
  return {
    user: userWithoutPassword,
    accessToken,
    refreshToken
  };
};
var getMyProfile = async (userId) => {
  const user = await prisma.user.findUniqueOrThrow({
    where: { id: userId },
    omit: {
      password: true
    },
    include: {
      profile: true
    }
  });
  return user;
};
var updateMyProfile = async (userId, payload) => {
  const { name, phone, bio, profilePhoto } = payload;
  const result = await prisma.$transaction(async (tx) => {
    if (name || phone) {
      await tx.user.update({
        where: { id: userId },
        data: {
          ...name && { name },
          ...phone && { phone }
        }
      });
    }
    if (bio !== void 0 || profilePhoto !== void 0) {
      await tx.profile.upsert({
        where: { userId },
        update: {
          ...bio !== void 0 && { bio },
          ...profilePhoto !== void 0 && { profilePhoto }
        },
        create: {
          userId,
          bio,
          profilePhoto
        }
      });
    }
    return await tx.user.findUniqueOrThrow({
      where: { id: userId },
      omit: { password: true },
      include: { profile: true }
    });
  });
  return result;
};
var authService = {
  registerUser,
  loginUser,
  getMyProfile,
  updateMyProfile
};

// src/utils/sendResponse.ts
var sendResponse = (res, data) => {
  res.status(data.statusCode).json({
    success: data.success,
    statusCode: data.statusCode,
    message: data.message,
    data: data.data,
    meta: data.meta
  });
};

// src/modules/auth/controller.ts
import httpStatus2 from "http-status";
var registerUser2 = catchAsync(async (req, res, next) => {
  const payload = req.body;
  const user = await authService.registerUser(payload);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus2.CREATED,
    message: "User registration successfully",
    data: {
      user
    }
  });
});
var loginUser2 = catchAsync(async (req, res, next) => {
  const payload = req.body;
  const { user, accessToken, refreshToken } = await authService.loginUser(payload);
  res.cookie("accessToken", accessToken, {
    httpOnly: true,
    secure: false,
    sameSite: "none",
    maxAge: 24 * 60 * 60 * 1e3
    // 1 day
  });
  res.cookie("refreshToken", refreshToken, {
    httpOnly: true,
    secure: false,
    sameSite: "none",
    maxAge: 7 * 24 * 60 * 60 * 1e3
    // 7 days
  });
  sendResponse(res, {
    success: true,
    statusCode: httpStatus2.OK,
    message: "User login successfully",
    data: {
      user,
      accessToken,
      refreshToken
    }
  });
});
var getMyProfile2 = catchAsync(async (req, res, next) => {
  const profile = await authService.getMyProfile(req.user?.id);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus2.OK,
    message: "User profile fetched successfully",
    data: {
      profile
    }
  });
});
var updateMyProfile2 = catchAsync(async (req, res) => {
  const userId = req.user?.id;
  const profile = await authService.updateMyProfile(userId, req.body);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus2.OK,
    message: "User profile updated successfully",
    data: {
      profile
    }
  });
});
var authController = {
  registerUser: registerUser2,
  loginUser: loginUser2,
  getMyProfile: getMyProfile2,
  updateMyProfile: updateMyProfile2
};

// src/middlewares/auth.ts
var auth = (...requiredRoles) => {
  return catchAsync(async (req, res, next) => {
    const token = req.cookies.accessToken ? req.cookies.accessToken : req.headers.authorization?.startsWith("Bearer") ? req.headers.authorization?.split(" ")[1] : req.headers.authorization;
    if (!token) {
      throw new Error(
        "You are not logged in. Please log in to access this resources."
      );
    }
    const verifiedToken = jwtUtils.verifyToken(
      token,
      config_default.jwt_access_secret
    );
    if (!verifiedToken.success) {
      throw new Error(verifiedToken.error);
    }
    const { email, name, id, role } = verifiedToken.data;
    if (requiredRoles.length && !requiredRoles.includes(role)) {
      throw new Error("Forbidden. You don't have permission to access this resource");
    }
    const user = await prisma.user.findUnique({
      where: {
        id,
        email,
        name,
        role
      }
    });
    if (!user) {
      throw new Error("User not found. Please log in again.");
    }
    if (user.status === "BANNED") {
      throw new Error("Your account has been banned. Please contact support.");
    }
    req.user = {
      email,
      name,
      id,
      role
    };
    next();
  });
};

// src/modules/auth/route.ts
var router = Router();
router.post("/register", authController.registerUser);
router.post("/login", authController.loginUser);
router.get(
  "/me",
  auth(UserRole.ADMIN, UserRole.LANDLORD, UserRole.TENANT),
  authController.getMyProfile
);
router.patch(
  "/me",
  auth(UserRole.ADMIN, UserRole.LANDLORD, UserRole.TENANT),
  authController.updateMyProfile
);
var authRoutes = router;

// src/modules/property/route.ts
import { Router as Router2 } from "express";

// src/modules/property/service.ts
var getAllProperties = async (query) => {
  const limit = query.limit ? Number(query.limit) : 10;
  const page = query.page ? Number(query.page) : 1;
  const skip = (page - 1) * limit;
  const sortBy = query.sortBy ? query.sortBy : "createdAt";
  const sortOrder = query.sortOrder ? query.sortOrder : "desc";
  const andConditions = [];
  if (query.searchTerm) {
    andConditions.push({
      OR: [
        {
          title: {
            contains: query.searchTerm,
            mode: "insensitive"
          }
        },
        {
          description: {
            contains: query.searchTerm,
            mode: "insensitive"
          }
        },
        {
          city: {
            contains: query.searchTerm,
            mode: "insensitive"
          }
        },
        {
          address: {
            contains: query.searchTerm,
            mode: "insensitive"
          }
        }
      ]
    });
  }
  if (query.location) {
    andConditions.push({
      OR: [
        {
          city: {
            contains: query.location,
            mode: "insensitive"
          }
        },
        {
          address: {
            contains: query.location,
            mode: "insensitive"
          }
        }
      ]
    });
  }
  if (query.minPrice || query.maxPrice) {
    andConditions.push({
      rentPrice: {
        ...query.minPrice && {
          gte: Number(query.minPrice)
        },
        ...query.maxPrice && {
          lte: Number(query.maxPrice)
        }
      }
    });
  }
  if (query.type) {
    andConditions.push({
      propertyType: {
        equals: query.type,
        mode: "insensitive"
      }
    });
  }
  if (query.categoryId) {
    andConditions.push({
      categoryId: query.categoryId
    });
  }
  if (query.status) {
    andConditions.push({
      status: query.status
    });
  }
  if (!query.status) {
    andConditions.push({
      status: "AVAILABLE"
    });
  }
  const properties = await prisma.property.findMany({
    where: {
      AND: andConditions
    },
    take: limit,
    skip,
    orderBy: {
      [sortBy]: sortOrder
    },
    include: {
      category: true,
      landlord: {
        select: {
          id: true,
          name: true,
          email: true,
          phone: true
        }
      }
    }
  });
  return properties;
};
var getPropertyById = async (id) => {
  const property = await prisma.property.findUniqueOrThrow({
    where: {
      id
    },
    include: {
      category: true,
      landlord: {
        select: {
          id: true,
          name: true,
          email: true,
          phone: true
        }
      },
      reviews: {
        include: {
          tenant: {
            select: {
              id: true,
              name: true
            }
          }
        }
      }
    }
  });
  return property;
};
var getAllCategories = async () => {
  const categories = await prisma.category.findMany({
    orderBy: {
      name: "asc"
    }
  });
  return categories;
};
var propertyService = {
  getAllProperties,
  getPropertyById,
  getAllCategories
};

// src/modules/property/controller.ts
import httpStatus3 from "http-status";
var getAllProperties2 = catchAsync(async (req, res) => {
  const result = await propertyService.getAllProperties(req.query);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus3.OK,
    message: "Properties retrieved successfully",
    data: result
  });
});
var getPropertyById2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const result = await propertyService.getPropertyById(id);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus3.OK,
    message: "Propertyretrieved successfully",
    data: result
  });
});
var getAllCategories2 = catchAsync(async (req, res) => {
  const result = await propertyService.getAllCategories();
  sendResponse(res, {
    success: true,
    statusCode: httpStatus3.OK,
    message: "Categories retrieved successfully",
    data: result
  });
});
var propertyController = {
  getAllProperties: getAllProperties2,
  getPropertyById: getPropertyById2,
  getAllCategories: getAllCategories2
};

// src/modules/property/route.ts
var router2 = Router2();
router2.get(
  "/",
  propertyController.getAllProperties
);
router2.get(
  "/:id",
  propertyController.getPropertyById
);
router2.get(
  "/categories",
  propertyController.getAllCategories
);
var propertyRoutes = router2;

// src/modules/landlord/route.ts
import { Router as Router3 } from "express";

// src/modules/landlord/service.ts
var createProperty = async (landlordId, data) => {
  const property = await prisma.property.create({
    data: {
      ...data,
      landlordId
    },
    include: {
      category: true,
      landlord: {
        select: {
          id: true,
          name: true,
          email: true,
          phone: true
        }
      }
    }
  });
  return property;
};
var updateProperty = async (propertyId, landlordId, payload) => {
  const property = await prisma.property.findUniqueOrThrow({
    where: {
      id: propertyId
      // landlordId,
    }
  });
  if (property.landlordId !== landlordId) {
    throw new Error("You are not the owner of this property!");
  }
  const result = await prisma.property.update({
    where: {
      id: propertyId
    },
    data: payload,
    include: {
      category: true,
      landlord: {
        select: {
          id: true,
          name: true,
          email: true,
          phone: true
        }
      }
    }
  });
  return result;
};
var deleteProperty = async (propertyId, landlordId) => {
  const property = await prisma.property.findFirstOrThrow({
    where: {
      id: propertyId,
      landlordId
    }
  });
  if (property.landlordId !== landlordId) {
    throw new Error("You are not the owner of this property!");
  }
  await prisma.property.delete({
    where: {
      id: propertyId
    }
  });
  return property;
};
var getLandlordRequests = async (landlordId) => {
  const requests = await prisma.rentalRequest.findMany({
    where: {
      property: {
        landlordId
      }
    },
    include: {
      tenant: {
        select: {
          id: true,
          name: true,
          email: true,
          phone: true
        }
      },
      property: {
        select: {
          id: true,
          title: true,
          address: true,
          city: true,
          rentPrice: true,
          status: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return requests;
};
var updateRentalRequest = async (requestId, landlordId, payload) => {
  const result = await prisma.$transaction(async (tx) => {
    const rentalRequest = await tx.rentalRequest.findFirstOrThrow({
      where: {
        id: requestId,
        property: {
          landlordId
        }
      }
    });
    const currentStatus = rentalRequest.status;
    const nextStatus = payload.status;
    if (currentStatus === nextStatus) {
      throw new Error(
        `Rental request is already ${nextStatus}`
      );
    }
    switch (currentStatus) {
      case RentalRequestStatus.PENDING:
        if (![
          RentalRequestStatus.APPROVED,
          RentalRequestStatus.REJECTED
        ].includes(nextStatus)) {
          throw new Error(
            "Pending request can only be APPROVED or REJECTED"
          );
        }
        break;
      case RentalRequestStatus.APPROVED:
        if (nextStatus !== RentalRequestStatus.ACTIVE) {
          throw new Error(
            "Approved request can only become ACTIVE"
          );
        }
        break;
      case RentalRequestStatus.ACTIVE:
        if (nextStatus !== RentalRequestStatus.COMPLETED) {
          throw new Error(
            "Active request can only become COMPLETED"
          );
        }
        break;
      case RentalRequestStatus.REJECTED:
        throw new Error(
          "Rejected request cannot be updated"
        );
      case RentalRequestStatus.COMPLETED:
        throw new Error(
          "Completed request cannot be updated"
        );
    }
    const updatedRequest = await tx.rentalRequest.update({
      where: {
        id: requestId
      },
      data: {
        status: nextStatus,
        approvedAt: nextStatus === RentalRequestStatus.APPROVED ? /* @__PURE__ */ new Date() : rentalRequest.approvedAt
      },
      include: {
        property: {
          select: {
            id: true,
            title: true,
            address: true,
            city: true,
            rentPrice: true
          }
        },
        tenant: {
          select: {
            id: true,
            name: true,
            email: true,
            phone: true
          }
        }
      }
    });
    if (nextStatus === RentalRequestStatus.APPROVED) {
      await tx.property.update({
        where: {
          id: rentalRequest.propertyId
        },
        data: {
          status: PropertyStatus.RENTED
        }
      });
    }
    return updatedRequest;
  });
  return result;
};
var landlordService = {
  createProperty,
  updateProperty,
  deleteProperty,
  getLandlordRequests,
  updateRentalRequest
};

// src/modules/landlord/controller.ts
import httpStatus4 from "http-status";
var createProperty2 = catchAsync(async (req, res) => {
  const result = await landlordService.createProperty(
    req.user.id,
    req.body
  );
  sendResponse(res, {
    success: true,
    statusCode: httpStatus4.CREATED,
    message: "Property created successfully",
    data: result
  });
});
var updateProperty2 = catchAsync(async (req, res, next) => {
  const landlordId = req.user?.id;
  const propertyId = req.params.id;
  if (!propertyId) {
    throw new Error("Property Id is required in params");
  }
  const payload = req.body;
  const result = await landlordService.updateProperty(
    propertyId,
    landlordId,
    payload
    // req.user!.id,
    // req.params.id as string,
    // req.body
  );
  sendResponse(res, {
    success: true,
    statusCode: httpStatus4.OK,
    message: "Property updated successfully",
    data: result
  });
});
var deleteProperty2 = catchAsync(async (req, res) => {
  const landlordId = req.user?.id;
  const propertyId = req.params.id;
  if (typeof propertyId !== "string" || propertyId.trim() === "") {
    throw new Error("Property Id Required in Params");
  }
  if (!landlordId) {
    throw new Error("Landlord Id not found");
  }
  await landlordService.deleteProperty(
    propertyId,
    landlordId
  );
  sendResponse(res, {
    success: true,
    statusCode: httpStatus4.OK,
    message: "Property deleted successfully",
    data: null
  });
});
var getLandlordRequests2 = catchAsync(
  async (req, res) => {
    const landlordId = req.user?.id;
    if (!landlordId) {
      throw new Error("Landlord Id not found");
    }
    const result = await landlordService.getLandlordRequests(
      landlordId
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus4.OK,
      message: "Rental requests retrieved successfully",
      data: result
    });
  }
);
var updateRentalRequest2 = catchAsync(
  async (req, res) => {
    const landlordId = req.user?.id;
    const requestId = req.params.id;
    if (!requestId) {
      throw new Error("Rental Request Id is required in params");
    }
    if (!landlordId) {
      throw new Error("Landlord Id not found");
    }
    const payload = req.body;
    const result = await landlordService.updateRentalRequest(
      requestId,
      landlordId,
      payload
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus4.OK,
      message: `Rental request ${payload.status.toLowerCase()} successfully`,
      data: result
    });
  }
);
var landlordController = {
  createProperty: createProperty2,
  updateProperty: updateProperty2,
  deleteProperty: deleteProperty2,
  getLandlordRequests: getLandlordRequests2,
  updateRentalRequest: updateRentalRequest2
};

// src/modules/landlord/route.ts
var router3 = Router3();
router3.post("/", auth(UserRole.LANDLORD), landlordController.createProperty);
router3.put(
  "/:id",
  auth(UserRole.LANDLORD),
  landlordController.updateProperty
);
router3.delete(
  "/:id",
  auth(UserRole.LANDLORD),
  landlordController.deleteProperty
);
router3.get(
  "/requests",
  auth(UserRole.LANDLORD),
  landlordController.getLandlordRequests
);
router3.patch(
  "/requests/:id",
  auth(UserRole.LANDLORD),
  landlordController.updateRentalRequest
);
var landlordRoutes = router3;

// src/modules/categories/routes.ts
import { Router as Router4 } from "express";

// src/modules/categories/service.ts
var createCategory = async (payload) => {
  const isExists = await prisma.category.findUnique({
    where: {
      name: payload.name
    }
  });
  if (isExists) {
    throw new Error("Category already exists");
  }
  return await prisma.category.create({
    data: payload
  });
};
var categoryService = {
  createCategory
  // getAllCategories
};

// src/modules/categories/controller.ts
import httpStatus5 from "http-status";
var createCategory2 = catchAsync(async (req, res) => {
  const result = await categoryService.createCategory(req.body);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus5.CREATED,
    message: "Categories retrieved successfully",
    data: result
  });
});
var categoryController = {
  createCategory: createCategory2
  // getAllCategories
};

// src/modules/categories/routes.ts
var router4 = Router4();
router4.post("/", categoryController.createCategory);
var categoryRoutes = router4;

// src/modules/rentalRequest/routes.ts
import { Router as Router5 } from "express";

// src/modules/rentalRequest/service.ts
var createRentalRequest = async (tenantId, data) => {
  const property = await prisma.property.findUniqueOrThrow({
    where: {
      id: data.propertyId
    }
  });
  if (property.status !== "AVAILABLE") {
    throw new Error("This property is not available for rent.");
  }
  const existingRequest = await prisma.rentalRequest.findFirst({
    where: {
      tenantId,
      propertyId: data.propertyId,
      status: "PENDING"
    }
  });
  if (existingRequest) {
    throw new Error(
      "You already have a pending rental request for this property."
    );
  }
  const rentalRequest = await prisma.rentalRequest.create({
    data: {
      tenantId,
      propertyId: data.propertyId,
      moveInDate: new Date(data.moveInDate),
      duration: Number(data.duration),
      // এখানে user-এর কাছ থেকে monthlyRent নেওয়া হচ্ছে না
      // Property-এর original rentPrice নেওয়া হচ্ছে
      monthlyRent: property.rentPrice
    },
    include: {
      property: {
        include: {
          category: true
        }
      }
    }
  });
  return rentalRequest;
};
var getMyRentalRequests = async (tenantId, query) => {
  const rentalRequests = await prisma.rentalRequest.findMany({
    where: {
      tenantId,
      ...query.status && {
        status: query.status
      }
    },
    orderBy: {
      createdAt: "desc"
    },
    include: {
      property: {
        include: {
          category: true,
          landlord: {
            omit: {
              password: true
            }
          }
        }
      },
      payment: true
    }
  });
  return rentalRequests;
};
var getRentalRequestById = async (rentalRequestId, tenantId) => {
  const rentalRequest = await prisma.rentalRequest.findFirstOrThrow({
    where: {
      id: rentalRequestId,
      tenantId
    },
    include: {
      property: {
        include: {
          category: true,
          landlord: {
            omit: {
              password: true
            }
          }
        }
      },
      payment: true
    }
  });
  return rentalRequest;
};
var rentalService = {
  createRentalRequest,
  getMyRentalRequests,
  getRentalRequestById
};

// src/modules/rentalRequest/controller.ts
import httpStatus6 from "http-status";
var createRentalRequest2 = catchAsync(
  async (req, res) => {
    const tenantId = req.user?.id;
    if (!tenantId) {
      throw new Error("Tenant Id not found");
    }
    const payload = req.body;
    const result = await rentalService.createRentalRequest(
      tenantId,
      payload
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus6.CREATED,
      message: "Rental request created successfully",
      data: result
    });
  }
);
var getMyRentalRequests2 = catchAsync(
  async (req, res) => {
    const tenantId = req.user?.id;
    if (!tenantId) {
      throw new Error("Tenant Id not found");
    }
    const query = req.query;
    const result = await rentalService.getMyRentalRequests(
      tenantId,
      query
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus6.OK,
      message: "Rental requests retrieved successfully",
      data: result
    });
  }
);
var getRentalRequestById2 = catchAsync(
  async (req, res) => {
    const tenantId = req.user?.id;
    const rentalRequestId = req.params.id;
    if (!tenantId) {
      throw new Error("Tenant Id not found");
    }
    if (!rentalRequestId) {
      throw new Error("Rental Request Id is required in params");
    }
    const result = await rentalService.getRentalRequestById(
      rentalRequestId,
      tenantId
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus6.OK,
      message: "Rental request details retrieved successfully",
      data: result
    });
  }
);
var rentalController = {
  createRentalRequest: createRentalRequest2,
  getMyRentalRequests: getMyRentalRequests2,
  getRentalRequestById: getRentalRequestById2
};

// src/modules/rentalRequest/routes.ts
var router5 = Router5();
router5.post(
  "/",
  auth(UserRole.TENANT),
  rentalController.createRentalRequest
);
router5.get(
  "/",
  auth(UserRole.TENANT),
  rentalController.getMyRentalRequests
);
router5.get(
  "/:id",
  auth(UserRole.TENANT),
  rentalController.getRentalRequestById
);
var rentalRoutes = router5;

// src/modules/admin/routes.ts
import { Router as Router6 } from "express";

// src/modules/admin/service.ts
var getAllUsers = async () => {
  const users = await prisma.user.findMany({
    omit: {
      password: true
    },
    include: {
      profile: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return users;
};
var updateUserStatus = async (userId, payload) => {
  if (payload.status !== UserStatus.ACTIVE && payload.status !== UserStatus.BANNED) {
    throw new Error(
      "Invalid status. Status must be either ACTIVE or BANNED."
    );
  }
  const user = await prisma.user.findUniqueOrThrow({
    where: {
      id: userId
    },
    select: {
      status: true
    }
  });
  if (user.status === payload.status) {
    throw new Error(
      `User status (${payload.status}) is already up to date.`
    );
  }
  const updatedUser = await prisma.user.update({
    where: {
      id: userId
    },
    data: {
      status: payload.status
    },
    omit: {
      password: true
    }
  });
  return updatedUser;
};
var getAllProperties3 = async () => {
  const properties = await prisma.property.findMany({
    orderBy: {
      createdAt: "desc"
    },
    include: {
      category: true,
      landlord: {
        omit: {
          password: true
        }
      },
      _count: {
        select: {
          rentalRequests: true,
          reviews: true
        }
      }
    }
  });
  return properties;
};
var getAllRentalRequests = async () => {
  const rentalRequests = await prisma.rentalRequest.findMany({
    orderBy: {
      createdAt: "desc"
    },
    include: {
      tenant: {
        omit: {
          password: true
        }
      },
      property: {
        include: {
          category: true,
          landlord: {
            omit: {
              password: true
            }
          }
        }
      },
      payment: true
    }
  });
  return rentalRequests;
};
var adminService = {
  getAllUsers,
  updateUserStatus,
  getAllProperties: getAllProperties3,
  getAllRentalRequests
};

// src/modules/admin/controller.ts
import httpStatus7 from "http-status";
var getAllUsers2 = catchAsync(
  async (req, res) => {
    const result = await adminService.getAllUsers();
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.OK,
      message: "Users retrieved successfully",
      data: result
    });
  }
);
var updateUserStatus2 = catchAsync(
  async (req, res) => {
    const userId = req.params.id;
    if (!userId) {
      throw new Error("User Id is required in params");
    }
    const result = await adminService.updateUserStatus(
      userId,
      req.body
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.OK,
      message: "User status updated successfully",
      data: result
    });
  }
);
var getAllProperties4 = catchAsync(
  async (req, res) => {
    const result = await adminService.getAllProperties();
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.OK,
      message: "Properties retrieved successfully",
      data: result
    });
  }
);
var getAllRentalRequests2 = catchAsync(
  async (req, res) => {
    const result = await adminService.getAllRentalRequests();
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.OK,
      message: "Rental requests retrieved successfully",
      data: result
    });
  }
);
var adminController = {
  getAllUsers: getAllUsers2,
  updateUserStatus: updateUserStatus2,
  getAllProperties: getAllProperties4,
  getAllRentalRequests: getAllRentalRequests2
};

// src/modules/admin/routes.ts
var router6 = Router6();
router6.get(
  "/users",
  auth(UserRole.ADMIN),
  adminController.getAllUsers
);
router6.patch(
  "/users/:id",
  auth(UserRole.ADMIN),
  adminController.updateUserStatus
);
router6.get(
  "/properties",
  auth(UserRole.ADMIN),
  adminController.getAllProperties
);
router6.get(
  "/rentals",
  auth(UserRole.ADMIN),
  adminController.getAllRentalRequests
);
var adminRoutes = router6;

// src/modules/review/routes.ts
import { Router as Router7 } from "express";

// src/modules/review/controller.ts
import httpStatus8 from "http-status";

// src/modules/review/service.ts
var createReview = async (tenantId, payload) => {
  const result = await prisma.$transaction(async (tx) => {
    const rental = await tx.rentalRequest.findFirstOrThrow({
      where: {
        tenantId,
        propertyId: payload.propertyId,
        status: RentalRequestStatus.COMPLETED
      }
    });
    const existingReview = await tx.review.findFirst({
      where: {
        tenantId,
        propertyId: payload.propertyId
      }
    });
    if (existingReview) {
      throw new Error(
        "You already reviewed this property"
      );
    }
    const review = await tx.review.create({
      data: {
        tenantId,
        propertyId: payload.propertyId,
        rating: payload.rating,
        comment: payload.comment
      }
    });
    return review;
  });
  return result;
};
var reviewService = {
  createReview
};

// src/modules/review/controller.ts
var createReview2 = catchAsync(
  async (req, res) => {
    const tenantId = req.user?.id;
    if (!tenantId) {
      throw new Error("Tenant Id not found");
    }
    const result = await reviewService.createReview(
      tenantId,
      req.body
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus8.CREATED,
      message: "Review submitted successfully",
      data: result
    });
  }
);
var reviewController = {
  createReview: createReview2
};

// src/modules/review/routes.ts
var router7 = Router7();
router7.post(
  "/",
  auth(UserRole.TENANT),
  reviewController.createReview
);
var reviewRoutes = router7;

// src/middlewares/notFound.ts
var notFound = (req, res) => {
  res.status(404).json({
    message: "Route not found",
    path: req.originalUrl,
    date: /* @__PURE__ */ new Date()
  });
};

// src/middlewares/globalErrorHandler.ts
import httpStatus9 from "http-status";
var globalErrorHandler = (err, req, res, next) => {
  console.log("Error:", err);
  let statusCode;
  let errorMessage = err.message || "Internal Server Error";
  let errorName = err.name || "Internal Server Error";
  if (err instanceof prismaNamespace_exports.PrismaClientValidationError) {
    statusCode = httpStatus9.BAD_REQUEST;
    errorMessage = "You have provided incorrect field type or missing fields";
  } else if (err instanceof prismaNamespace_exports.PrismaClientKnownRequestError) {
    if (err.code === "P2002") {
      statusCode = httpStatus9.BAD_REQUEST, errorMessage = "Duplicate Key Error";
    } else if (err.code === "P2003") {
      statusCode = httpStatus9.BAD_REQUEST, errorMessage = "Foreign Key constraint failed";
    } else if (err.code === "P2025") {
      statusCode = httpStatus9.BAD_REQUEST;
      errorMessage = "An operatin faoled because it depends on one or more records that were required but not found";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientInitializationError) {
    if (err.errorCode === "P100") {
      statusCode = httpStatus9.UNAUTHORIZED;
      errorMessage = "Authentication failed against database server. PLease check your Credentials";
    } else if (err.errorCode === "P1001") {
      statusCode = httpStatus9.BAD_REQUEST;
      errorMessage = "Can't reach database server";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientUnknownRequestError) {
    statusCode = httpStatus9.INTERNAL_SERVER_ERROR;
    errorMessage = "Error Occured during query execution";
  }
  res.status(httpStatus9.INTERNAL_SERVER_ERROR).json({
    success: false,
    statusCode: statusCode || httpStatus9.INTERNAL_SERVER_ERROR,
    name: errorName,
    message: errorMessage,
    error: err.stack
  });
};

// src/modules/payment/routes.ts
import express, { Router as Router8 } from "express";

// src/modules/payment/controller.ts
import httpStatus10 from "http-status";

// src/modules/payment/service.ts
import Stripe from "stripe";
var getStripeInstance = () => {
  if (!config_default.stripe_secret_key) {
    throw new Error("STRIPE_SECRET_KEY is missing in environment variables.");
  }
  return new Stripe(config_default.stripe_secret_key);
};
var createCheckoutSession = async (tenantId, payload) => {
  if (!payload || !payload.rentalRequestId) {
    throw new Error("rentalRequestId is required in request body.");
  }
  const { rentalRequestId, successUrl, cancelUrl } = payload;
  const rentalRequest = await prisma.rentalRequest.findUniqueOrThrow({
    where: {
      id: rentalRequestId
    },
    include: {
      property: true
    }
  });
  if (rentalRequest.tenantId !== tenantId) {
    throw new Error("You are not authorized to pay for this rental request.");
  }
  if (rentalRequest.status !== RentalRequestStatus.APPROVED) {
    throw new Error(
      `Cannot create payment. Rental request status is ${rentalRequest.status}. It must be APPROVED.`
    );
  }
  const existingPayment = await prisma.payment.findUnique({
    where: {
      rentalRequestId
    }
  });
  if (existingPayment && existingPayment.status === PaymentStatus.SUCCESS) {
    throw new Error("Payment for this rental request has already been completed.");
  }
  const totalAmount = Number(rentalRequest.monthlyRent) * rentalRequest.duration;
  const amountInCents = Math.round(totalAmount * 100);
  const stripe = getStripeInstance();
  const appUrl = config_default.app_url || "http://localhost:3000";
  const defaultSuccessUrl = `${appUrl}/payment-success?session_id={CHECKOUT_SESSION_ID}&rental_request_id=${rentalRequestId}`;
  const defaultCancelUrl = `${appUrl}/payment-cancel?rental_request_id=${rentalRequestId}`;
  const session = await stripe.checkout.sessions.create({
    payment_method_types: ["card"],
    mode: "payment",
    line_items: [
      {
        price_data: {
          currency: "usd",
          product_data: {
            name: rentalRequest.property.title,
            description: `Rent payment for ${rentalRequest.duration} month(s) - ${rentalRequest.property.address}`
          },
          unit_amount: amountInCents
        },
        quantity: 1
      }
    ],
    success_url: successUrl || defaultSuccessUrl,
    cancel_url: cancelUrl || defaultCancelUrl,
    metadata: {
      rentalRequestId: rentalRequest.id,
      tenantId,
      propertyId: rentalRequest.propertyId
    },
    client_reference_id: rentalRequest.id
  });
  const payment = await prisma.payment.upsert({
    where: {
      rentalRequestId
    },
    update: {
      transactionId: session.id,
      amount: totalAmount,
      provider: PaymentProvider.STRIPE,
      status: PaymentStatus.PENDING
    },
    create: {
      rentalRequestId,
      transactionId: session.id,
      amount: totalAmount,
      provider: PaymentProvider.STRIPE,
      status: PaymentStatus.PENDING
    }
  });
  return {
    checkoutUrl: session.url,
    sessionId: session.id,
    payment
  };
};
var confirmPayment = async (tenantId, payload) => {
  if (!payload) {
    throw new Error("Session ID or Payment Intent ID is required in request body.");
  }
  const { sessionId, paymentIntentId, rentalRequestId } = payload;
  const idToSearch = sessionId || paymentIntentId || rentalRequestId;
  if (!idToSearch) {
    throw new Error("Session ID, Payment Intent ID, or Rental Request ID is required.");
  }
  const payment = await prisma.payment.findFirst({
    where: {
      OR: [
        { transactionId: idToSearch },
        { rentalRequestId: idToSearch }
      ]
    },
    include: {
      rentalRequest: {
        include: {
          property: true
        }
      }
    }
  });
  if (!payment) {
    throw new Error("Payment record not found.");
  }
  if (payment.rentalRequest.tenantId !== tenantId) {
    throw new Error("You are not authorized to confirm this payment.");
  }
  if (payment.status === PaymentStatus.SUCCESS) {
    return {
      message: "Payment is already marked as SUCCESS.",
      payment
    };
  }
  const stripe = getStripeInstance();
  let isPaid = false;
  let paymentMethod = "card";
  if (idToSearch.startsWith("cs_")) {
    const session = await stripe.checkout.sessions.retrieve(idToSearch);
    if (session.payment_status === "paid") {
      isPaid = true;
      paymentMethod = session.payment_method_types?.[0] || "card";
    }
  } else if (idToSearch.startsWith("pi_")) {
    const paymentIntent = await stripe.paymentIntents.retrieve(idToSearch);
    if (paymentIntent.status === "succeeded") {
      isPaid = true;
      paymentMethod = paymentIntent.payment_method_types?.[0] || "card";
    }
  } else if (payment.transactionId?.startsWith("cs_")) {
    const session = await stripe.checkout.sessions.retrieve(payment.transactionId);
    if (session.payment_status === "paid") {
      isPaid = true;
      paymentMethod = session.payment_method_types?.[0] || "card";
    }
  } else if (payment.transactionId?.startsWith("pi_")) {
    const paymentIntent = await stripe.paymentIntents.retrieve(payment.transactionId);
    if (paymentIntent.status === "succeeded") {
      isPaid = true;
      paymentMethod = paymentIntent.payment_method_types?.[0] || "card";
    }
  }
  if (isPaid) {
    const result = await prisma.$transaction(async (tx) => {
      const updatedPayment = await tx.payment.update({
        where: {
          id: payment.id
        },
        data: {
          status: PaymentStatus.SUCCESS,
          paidAt: /* @__PURE__ */ new Date(),
          paymentMethod
        }
      });
      const updatedRentalRequest = await tx.rentalRequest.update({
        where: {
          id: payment.rentalRequestId
        },
        data: {
          status: RentalRequestStatus.ACTIVE
        }
      });
      await tx.property.update({
        where: {
          id: payment.rentalRequest.propertyId
        },
        data: {
          status: PropertyStatus.RENTED
        }
      });
      return {
        payment: updatedPayment,
        rentalRequest: updatedRentalRequest
      };
    });
    return result;
  } else {
    await prisma.payment.update({
      where: {
        id: payment.id
      },
      data: {
        status: PaymentStatus.FAILED
      }
    });
    throw new Error("Stripe checkout status is unpaid. Payment not completed.");
  }
};
var getMyPaymentHistory = async (tenantId) => {
  const payments = await prisma.payment.findMany({
    where: {
      rentalRequest: {
        tenantId
      }
    },
    include: {
      rentalRequest: {
        include: {
          property: {
            select: {
              id: true,
              title: true,
              address: true,
              city: true,
              rentPrice: true
            }
          }
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return payments;
};
var getPaymentById = async (paymentId, userId, role) => {
  const payment = await prisma.payment.findUniqueOrThrow({
    where: {
      id: paymentId
    },
    include: {
      rentalRequest: {
        include: {
          property: {
            select: {
              id: true,
              title: true,
              address: true,
              city: true,
              landlordId: true
            }
          },
          tenant: {
            select: {
              id: true,
              name: true,
              email: true
            }
          }
        }
      }
    }
  });
  const isTenant = payment.rentalRequest.tenantId === userId;
  const isLandlord = payment.rentalRequest.property.landlordId === userId;
  const isAdmin = role === "ADMIN";
  if (!isTenant && !isLandlord && !isAdmin) {
    throw new Error("You are not authorized to view this payment.");
  }
  return payment;
};
var handleStripeWebhook = async (signature, rawBody) => {
  const stripe = getStripeInstance();
  const webhookSecret = config_default.stripe_webhook_secret;
  if (!webhookSecret) {
    throw new Error("STRIPE_WEBHOOK_SECRET is missing in environment variables.");
  }
  let event;
  try {
    event = stripe.webhooks.constructEvent(rawBody, signature, webhookSecret);
  } catch (err) {
    throw new Error(`Webhook Signature Verification Failed: ${err.message}`);
  }
  const completePaymentInDb = async (rentalRequestId, transactionId, paymentMethod) => {
    const payment = await prisma.payment.findFirst({
      where: {
        OR: [
          ...transactionId ? [{ transactionId }] : [],
          ...rentalRequestId ? [{ rentalRequestId }] : []
        ]
      },
      include: { rentalRequest: true }
    });
    if (payment && payment.status !== PaymentStatus.SUCCESS) {
      await prisma.$transaction(async (tx) => {
        await tx.payment.update({
          where: { id: payment.id },
          data: {
            status: PaymentStatus.SUCCESS,
            paidAt: /* @__PURE__ */ new Date(),
            paymentMethod: paymentMethod || "card",
            ...transactionId ? { transactionId } : {}
          }
        });
        await tx.rentalRequest.update({
          where: { id: payment.rentalRequestId },
          data: { status: RentalRequestStatus.ACTIVE }
        });
        await tx.property.update({
          where: { id: payment.rentalRequest.propertyId },
          data: { status: PropertyStatus.RENTED }
        });
      });
    }
  };
  switch (event.type) {
    case "checkout.session.completed": {
      const session = event.data.object;
      if (session.payment_status === "paid") {
        const rentalRequestId = session.metadata?.rentalRequestId || session.client_reference_id;
        await completePaymentInDb(
          rentalRequestId,
          session.id,
          session.payment_method_types?.[0]
        );
      }
      break;
    }
    case "payment_intent.succeeded": {
      const paymentIntent = event.data.object;
      const rentalRequestId = paymentIntent.metadata?.rentalRequestId;
      await completePaymentInDb(
        rentalRequestId,
        paymentIntent.id,
        paymentIntent.payment_method_types?.[0]
      );
      break;
    }
    case "payment_intent.payment_failed": {
      const paymentIntent = event.data.object;
      await prisma.payment.updateMany({
        where: { transactionId: paymentIntent.id },
        data: { status: PaymentStatus.FAILED }
      });
      break;
    }
    case "checkout.session.expired": {
      const session = event.data.object;
      await prisma.payment.updateMany({
        where: { transactionId: session.id },
        data: { status: PaymentStatus.FAILED }
      });
      break;
    }
  }
  return { received: true };
};
var paymentService = {
  createCheckoutSession,
  createPaymentIntent: createCheckoutSession,
  confirmPayment,
  getMyPaymentHistory,
  getPaymentById,
  handleStripeWebhook
};

// src/modules/payment/controller.ts
var createCheckoutSession2 = catchAsync(async (req, res) => {
  const tenantId = req.user?.id;
  if (!tenantId) {
    throw new Error("Tenant ID not found in session.");
  }
  const result = await paymentService.createCheckoutSession(tenantId, req.body);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus10.CREATED,
    message: "Stripe checkout session created successfully",
    data: result
  });
});
var confirmPayment2 = catchAsync(async (req, res) => {
  const tenantId = req.user?.id;
  if (!tenantId) {
    throw new Error("Tenant ID not found in session.");
  }
  const result = await paymentService.confirmPayment(tenantId, req.body);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus10.OK,
    message: "Payment confirmed and rental request activated successfully",
    data: result
  });
});
var getMyPaymentHistory2 = catchAsync(async (req, res) => {
  const tenantId = req.user?.id;
  if (!tenantId) {
    throw new Error("Tenant ID not found in session.");
  }
  const result = await paymentService.getMyPaymentHistory(tenantId);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus10.OK,
    message: "Payment history retrieved successfully",
    data: result
  });
});
var getPaymentById2 = catchAsync(async (req, res) => {
  const userId = req.user?.id;
  const role = req.user?.role;
  const paymentId = req.params.id;
  if (!userId || !role) {
    throw new Error("User credentials not found in session.");
  }
  if (!paymentId) {
    throw new Error("Payment ID is required in route params.");
  }
  const result = await paymentService.getPaymentById(paymentId, userId, role);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus10.OK,
    message: "Payment details retrieved successfully",
    data: result
  });
});
var handleWebhook = catchAsync(async (req, res) => {
  const signature = req.headers["stripe-signature"];
  if (!signature) {
    throw new Error("Missing stripe-signature header.");
  }
  const result = await paymentService.handleStripeWebhook(signature, req.body);
  res.status(httpStatus10.OK).json(result);
});
var paymentController = {
  createCheckoutSession: createCheckoutSession2,
  createPaymentIntent: createCheckoutSession2,
  confirmPayment: confirmPayment2,
  getMyPaymentHistory: getMyPaymentHistory2,
  getPaymentById: getPaymentById2,
  handleWebhook
};

// src/modules/payment/routes.ts
var router8 = Router8();
router8.post(
  "/webhook",
  express.raw({ type: "application/json" }),
  paymentController.handleWebhook
);
router8.post(
  "/create",
  auth(UserRole.TENANT),
  paymentController.createCheckoutSession
);
router8.post(
  "/create-checkout-session",
  auth(UserRole.TENANT),
  paymentController.createCheckoutSession
);
router8.post(
  "/confirm",
  auth(UserRole.TENANT),
  paymentController.confirmPayment
);
router8.get(
  "/",
  auth(UserRole.TENANT),
  paymentController.getMyPaymentHistory
);
router8.get(
  "/:id",
  auth(UserRole.TENANT, UserRole.LANDLORD, UserRole.ADMIN),
  paymentController.getPaymentById
);
var paymentRoutes = router8;

// src/app.ts
var app = express2();
app.use(cors({
  origin: config_default.app_url,
  credentials: true
}));
app.use(
  "/api/payments/webhook",
  express2.raw({ type: "application/json" })
);
app.use(express2.json());
app.use(express2.urlencoded({ extended: true }));
app.use(cookieParser());
app.get("/", async (req, res) => {
  res.send("Hello, RestNest!");
});
app.use("/api/auth", authRoutes);
app.use("/api/properties", propertyRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/landlord/properties", landlordRoutes);
app.use("/api/rentals", rentalRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/reviews", reviewRoutes);
app.use("/api/payments", paymentRoutes);
app.use(notFound);
app.use(globalErrorHandler);
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
